// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TrackClassSubscriberApp.cxx
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "TrackClassSubscriberApp.hpp"

#include <condition_variable>
#include <stdexcept>

#include <fastdds/dds/core/status/SubscriptionMatchedStatus.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/qos/DataReaderQos.hpp>
#include <fastdds/dds/subscriber/qos/SubscriberQos.hpp>
#include <fastdds/dds/subscriber/SampleInfo.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>

#include "TrackClassPubSubTypes.hpp"
#include "customconfig.h"

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QProcessEnvironment>
#include <QWriteLocker>
#include <QSettings>
#include <atomic>

using namespace eprosima::fastdds::dds;

namespace {
std::atomic<int> g_trackDdsSampleLogCount { 0 };

struct TrackDdsConfig {
    bool useProfile = true;
    QString xmlFile = QStringLiteral("trackclass_recv_multi.xml");
    QString participantProfile = QStringLiteral("participant_trackclass_recv_multi");
    QString topicFuseTrack = QStringLiteral("TrackDataClassTopic_FuseTrack");
    QString topicRadarTrack1 = QStringLiteral("TrackDataClassTopic_RadarTrack1");
    QString topicRadarTrack2 = QStringLiteral("TrackDataClassTopic_RadarTrack2");
    QString topicAisTrack = QStringLiteral("TrackDataClassTopic_AISTrack");
    QString topicUavPoseTrack = QStringLiteral("TrackDataClassTopic_UAVPoseTrack");
    QString topicBirdRadarTrack = QStringLiteral("TrackDataClassTopic_BirdRadarTrack");
    QString topicAutoBirdRadarTrack = QStringLiteral("TrackDataClassTopic_AutoBirdRadarTrack");
    QString topicFuseBirdRadarTrack = QStringLiteral("TrackDataClassTopic_FuseBirdRadarTrack");
    QString topicKuRadarTrack = QStringLiteral("TrackDataClassTopic_KuRadarTrack");
    bool enableAutoBirdRadar = true;
    bool enableFuseBirdRadar = true;
    bool enableKuRadar = true;
    int mode = 0;
};

TrackDdsConfig loadTrackDdsConfig()
{
    TrackDdsConfig c;
    QSettings s(QStringLiteral("Config.ini"), QSettings::IniFormat);
    c.useProfile = s.value(QStringLiteral("DDS/TrackUseProfile"), 1).toInt() != 0;
    c.xmlFile = s.value(QStringLiteral("DDS/TrackXml"), c.xmlFile).toString();
    c.participantProfile = s.value(QStringLiteral("DDS/TrackParticipantProfile"), c.participantProfile).toString();
    c.topicFuseTrack = s.value(QStringLiteral("DDS/TrackTopicFuse"), c.topicFuseTrack).toString();
    c.topicRadarTrack1 = s.value(QStringLiteral("DDS/TrackTopicRadar1"), c.topicRadarTrack1).toString();
    c.topicRadarTrack2 = s.value(QStringLiteral("DDS/TrackTopicRadar2"), c.topicRadarTrack2).toString();
    c.topicAisTrack = s.value(QStringLiteral("DDS/TrackTopicAIS"), c.topicAisTrack).toString();
    c.topicUavPoseTrack = s.value(QStringLiteral("DDS/TrackTopicUAVPose"), c.topicUavPoseTrack).toString();
    c.topicBirdRadarTrack = s.value(QStringLiteral("DDS/TrackTopicBirdRadar"), c.topicBirdRadarTrack).toString();
    c.topicAutoBirdRadarTrack = s.value(QStringLiteral("DDS/TrackTopicAutoBirdRadar"), c.topicAutoBirdRadarTrack).toString();
    c.topicFuseBirdRadarTrack = s.value(QStringLiteral("DDS/TrackTopicFuseBirdRadar"), c.topicFuseBirdRadarTrack).toString();
    c.enableAutoBirdRadar = s.value(QStringLiteral("DDS/TrackEnableAutoBirdRadar"), 1).toInt() != 0;
    c.enableFuseBirdRadar = s.value(QStringLiteral("DDS/TrackEnableFuseBirdRadar"), 1).toInt() != 0;
    c.topicKuRadarTrack = s.value(QStringLiteral("DDS/TrackTopicKuRadar"), c.topicKuRadarTrack).toString();
    c.enableKuRadar = s.value(QStringLiteral("DDS/TrackEnableKuRadar"), 1).toInt() != 0;
    c.mode = s.value(QStringLiteral("AlarmLogic/Mode"), 0).toInt();
    return c;
}
}

TrackClassSubscriberApp::TrackClassSubscriberApp(
    const int& domain_id)
    : factory_(nullptr)
    , participant_(nullptr)
    , subscriber_(nullptr)
    , topic_(nullptr)
    , topic2_(nullptr)
    , topic3_(nullptr)
    , topic4_(nullptr)
    , topic5_(nullptr)
    , topic6_(nullptr)
    , topic7_(nullptr)
    , topic8_(nullptr)
    , topic9_(nullptr)
    , reader_(nullptr)
    , reader2_(nullptr)
    , reader3_(nullptr)
    , reader4_(nullptr)
    , reader5_(nullptr)
    , reader6_(nullptr)
    , reader7_(nullptr)
    , reader8_(nullptr)
    , reader9_(nullptr)
    , type_(new TrackDataClassPubSubType())
    , samples_received_(0)
    , stop_(false)
{
    gConfig = CustomConfig::getInstance();
    const TrackDdsConfig ddsCfg = loadTrackDdsConfig();
    m_mode = ddsCfg.mode;
    m_topicNameFuseTrack = ddsCfg.topicFuseTrack;
    m_topicNameRadarTrack1 = ddsCfg.topicRadarTrack1;
    m_topicNameRadarTrack2 = ddsCfg.topicRadarTrack2;
    m_topicNameAisTrack = ddsCfg.topicAisTrack;
    m_topicNameUavPoseTrack = ddsCfg.topicUavPoseTrack;
    m_topicNameBirdRadarTrack = ddsCfg.topicBirdRadarTrack;
    m_topicNameAutoBirdRadarTrack = ddsCfg.topicAutoBirdRadarTrack;
    m_topicNameFuseBirdRadarTrack = ddsCfg.topicFuseBirdRadarTrack;
    m_topicNameKuRadarTrack = ddsCfg.topicKuRadarTrack;
    connect(&m_clearTimer, &QTimer::timeout, this, &TrackClassSubscriberApp::slotClearTrack);
    m_clearTimer.start(2000);
    // Create the participant
    DomainParticipantQos pqos = PARTICIPANT_QOS_DEFAULT;
    pqos.name("TrackDataClass_sub_participant");
    factory_ = DomainParticipantFactory::get_shared_instance();
    if (ddsCfg.useProfile)
    {
        // 与 track_class 一致：用 get_instance() 加载 XML 并创建 participant（避免与部分环境下 shared 路径差异）
        DomainParticipantFactory::get_instance()->load_XML_profiles_file(ddsCfg.xmlFile.toStdString());
        qDebug() << "TrackClassSubscriberApp: load_XML_profiles_file" << ddsCfg.xmlFile << "domain_id" << domain_id;
        participant_ = DomainParticipantFactory::get_instance()->create_participant_with_profile(
            domain_id, ddsCfg.participantProfile.toStdString());
        qDebug() << "TrackClassSubscriberApp: participant_profile" << ddsCfg.participantProfile << "created";
    }
    else
    {
        participant_ = factory_->create_participant(domain_id, pqos, nullptr, StatusMask::none());
    }

    if (participant_ == nullptr)
    {
        throw std::runtime_error("TrackDataClass Participant initialization failed");
    }

    qDebug() << "TrackClassSubscriberApp: Register the track class type to the participant";
    // Register the type
    type_.register_type(participant_);

    // Create the subscriber
    SubscriberQos sub_qos = SUBSCRIBER_QOS_DEFAULT;
    participant_->get_default_subscriber_qos(sub_qos);
    subscriber_ = participant_->create_subscriber(sub_qos, nullptr, StatusMask::none());
    if (subscriber_ == nullptr)
    {
        throw std::runtime_error("TrackDataClass Subscriber initialization failed");
    }

    // Create the topic
    /*TopicQos topic_qos = TOPIC_QOS_DEFAULT;
    participant_->get_default_topic_qos(topic_qos);
    topic_ = participant_->create_topic("TrackClassTopic", type_.get_type_name(), topic_qos);
    if (topic_ == nullptr)
    {
        throw std::runtime_error("TrackDataClass Topic initialization failed");
    }*/

    // CREATE TOPICS FROM Config.ini [DDS]
    topic_ = participant_->create_topic(m_topicNameFuseTrack.toStdString(), type_.get_type_name(), TOPIC_QOS_DEFAULT);
    topic2_ = participant_->create_topic(m_topicNameRadarTrack1.toStdString(), type_.get_type_name(), TOPIC_QOS_DEFAULT);
    topic3_ = participant_->create_topic(m_topicNameRadarTrack2.toStdString(), type_.get_type_name(), TOPIC_QOS_DEFAULT);
    topic4_ = participant_->create_topic(m_topicNameAisTrack.toStdString(), type_.get_type_name(), TOPIC_QOS_DEFAULT);
    topic5_ = participant_->create_topic(m_topicNameUavPoseTrack.toStdString(), type_.get_type_name(), TOPIC_QOS_DEFAULT);
    topic6_ = participant_->create_topic(m_topicNameBirdRadarTrack.toStdString(), type_.get_type_name(), TOPIC_QOS_DEFAULT);
    if (ddsCfg.enableAutoBirdRadar && !m_topicNameAutoBirdRadarTrack.trimmed().isEmpty())
        topic7_ = participant_->create_topic(m_topicNameAutoBirdRadarTrack.toStdString(), type_.get_type_name(), TOPIC_QOS_DEFAULT);
    if (ddsCfg.enableFuseBirdRadar && !m_topicNameFuseBirdRadarTrack.trimmed().isEmpty())
        topic8_ = participant_->create_topic(m_topicNameFuseBirdRadarTrack.toStdString(), type_.get_type_name(), TOPIC_QOS_DEFAULT);
    if (ddsCfg.enableKuRadar && !m_topicNameKuRadarTrack.trimmed().isEmpty())
        topic9_ = participant_->create_topic(m_topicNameKuRadarTrack.toStdString(), type_.get_type_name(), TOPIC_QOS_DEFAULT);
    // Create the reader
    DataReaderQos reader_qos = DATAREADER_QOS_DEFAULT;
    subscriber_->get_default_datareader_qos(reader_qos);
    reader_qos.reliability().kind = ReliabilityQosPolicyKind::RELIABLE_RELIABILITY_QOS;
    reader_qos.durability().kind = DurabilityQosPolicyKind::TRANSIENT_LOCAL_DURABILITY_QOS;
    reader_qos.history().kind = HistoryQosPolicyKind::KEEP_ALL_HISTORY_QOS;
    reader_ = subscriber_->create_datareader(topic_, reader_qos, this, StatusMask::all());

    reader2_ = subscriber_->create_datareader(topic2_, reader_qos, this, StatusMask::all());

    reader3_ = subscriber_->create_datareader(topic3_, reader_qos, this, StatusMask::all());

    reader4_ = subscriber_->create_datareader(topic4_, reader_qos, this, StatusMask::all());

    reader5_ = subscriber_->create_datareader(topic5_, reader_qos, this, StatusMask::all());

    reader6_ = subscriber_->create_datareader(topic6_, reader_qos, this, StatusMask::all());
    if (topic7_ != nullptr)
        reader7_ = subscriber_->create_datareader(topic7_, reader_qos, this, StatusMask::all());
    if (topic8_ != nullptr)
        reader8_ = subscriber_->create_datareader(topic8_, reader_qos, this, StatusMask::all());
    if (topic9_ != nullptr)
        reader9_ = subscriber_->create_datareader(topic9_, reader_qos, this, StatusMask::all());

}

TrackClassSubscriberApp::~TrackClassSubscriberApp()
{
    if (nullptr != participant_)
    {
        // Delete DDS entities contained within the DomainParticipant
        participant_->delete_contained_entities();

        // Delete DomainParticipant
        if (factory_)
            factory_->delete_participant(participant_);
        else
            DomainParticipantFactory::get_instance()->delete_participant(participant_);
    }
}

void TrackClassSubscriberApp::on_subscription_matched(
    DataReader* /*reader*/,
    const SubscriptionMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        std::cout << "TrackDataClass Subscriber matched." << std::endl;
    }
    else if (info.current_count_change == -1)
    {
        std::cout << "TrackDataClass Subscriber unmatched." << std::endl;
    }
    else
    {
        std::cout << info.current_count_change
            << " is not a valid value for SubscriptionMatchedStatus current count change" << std::endl;
    }
}

void TrackClassSubscriberApp::on_data_available(
    DataReader* reader)
{
    m_dataMutex.lock();
    QWriteLocker trackWriteLocker(&((CustomConfig*)gConfig)->m_trackDataLock);
    TrackDataClass st;
    SampleInfo info;
    while ((!is_stopped()) && (RETCODE_OK == reader->take_next_sample(&st, &info)))
    {
        //qDebug() << "TrackClassSubscriberApp: on_data_available: take_next_sample";
        if ((info.instance_state == ALIVE_INSTANCE_STATE) && info.valid_data)
        {
            if (qEnvironmentVariableIntValue("ALARMSYS_TRACE_TRACK") != 0) {
                const int n = ++g_trackDdsSampleLogCount;
                if (n <= 5 || (n % 500 == 0)) {
                    const std::string tname = reader->get_topicdescription()->get_name();
                    qInfo() << "[TrackDDS] topic" << QString::fromStdString(tname)
                            << "sample#" << n << "trackId(field)=" << st.trackId() << "reserved4=" << st.reserved4();
                }
            }
            const QString topicName = QString::fromStdString(reader->get_topicdescription()->get_name());
            if (topicName != m_topicNameAisTrack)
            {
                if (info.valid_data)
                {
                    SPxPacketTrackExtended track;
                    int trackid = st.trackId();
                    track.norm.min.id = st.trackId();
                    track.longDegs = st.longitude();
                    track.latDegs = st.latitude();
                    track.altitudeMetres = st.height();
                    track.norm.min.rangeMetres = st.distance();
                    track.norm.min.azimuthDegrees = st.azimuth();
                    track.norm.min.courseDegrees = st.course();
                    track.norm.min.speedMps = st.speed();
                    track.norm.min.sizeDegrees = st.sizeDegrees();
                    track.norm.min.sizeMetres = st.sizeMetres();

                    track.msgTimeSecs = static_cast<uint32_t>(QDateTime::currentDateTime().toSecsSinceEpoch());
                    track.msgTimeUsecs = 0;
                    track.secondary.uniqueID = st.uniqueId();
                    track.norm.reserved3 = st.threatScore();
                    track.fusion.sensors = st.sensors();

                    for (int i = 0; i < 8; i++)
                        track.fusion.trackID[i] = st.trackID().at(i);
                    if (topicName == m_topicNameFuseTrack)
                    {
                        if (m_mode == 1)
                        {
                            trackid = st.reserved4();
                            track.norm.min.id = trackid;
                            ((CustomConfig*)gConfig)->m_mapFuseTrack.insert(trackid, track);
                            if (!((CustomConfig*)gConfig)->m_mapFuseTrail[trackid].contains(QPointF(track.latDegs, track.longDegs)))
                            {
                                if (((CustomConfig*)gConfig)->m_mapFuseTrail[trackid].size() > 15)
                                {
                                    ((CustomConfig*)gConfig)->m_mapFuseTrail[trackid].removeFirst();
                                }
                                ((CustomConfig*)gConfig)->m_mapFuseTrail[trackid].append(QPointF(track.latDegs, track.longDegs));
                            }
                        }
                        else
                        {
                            trackid = st.trackId();
                            track.norm.min.id = trackid;
                            if (trackid < 10000)
                            {
                                ((CustomConfig*)gConfig)->m_mapFuseTrack.insert(trackid, track);
                                if (!((CustomConfig*)gConfig)->m_mapFuseTrail[trackid].contains(QPointF(track.latDegs, track.longDegs)))
                                {
                                    if (((CustomConfig*)gConfig)->m_mapFuseTrail[trackid].size() > 10)
                                    {
                                        ((CustomConfig*)gConfig)->m_mapFuseTrail[trackid].removeFirst();
                                    }
                                    ((CustomConfig*)gConfig)->m_mapFuseTrail[trackid].append(QPointF(track.latDegs, track.longDegs));
                                }
                            }
                        }
                    }
                    else if (topicName == m_topicNameFuseBirdRadarTrack)
                    {
                        QString zibaowei;
                        QString reserved6Str = QString::fromStdString(st.reserved6());
                        if (!reserved6Str.isEmpty())
                        {
                            QJsonParseError parseError;
                            QJsonDocument doc = QJsonDocument::fromJson(reserved6Str.toUtf8(), &parseError);
                            if (parseError.error == QJsonParseError::NoError && doc.isArray())
                            {
                                QJsonArray arr = doc.array();
                                QStringList trackIds;
                                for (const QJsonValue& val : arr)
                                {
                                    QJsonObject obj = val.toObject();
                                    QString dataSourceId = obj["dataSourceId"].toString();
                                    if (dataSourceId != "tan_niao" && obj.contains("trackId"))
                                    {
                                        trackIds << QString::number(obj["trackId"].toInt());
                                    }
                                }
                                zibaowei = trackIds.join(",");
                            }
                        }
                        track.fusion.trackID[0] = zibaowei.toInt();
                        int catid = st.trackCategoryId();
                        if (catid == 3)
                        {
                            track.norm.min.reserved1 = 3;
                        }
                        else
                        {
                            track.norm.min.reserved1 = 1;
                        }

                        ((CustomConfig*)gConfig)->m_mapBirdFuseTrack.insert(trackid, track);
                        if (!((CustomConfig*)gConfig)->m_mapBirdFuseTrail[trackid].contains(QPointF(track.latDegs, track.longDegs)))
                        {
                            if (((CustomConfig*)gConfig)->m_mapBirdFuseTrail[trackid].size() > 10)
                            {
                                ((CustomConfig*)gConfig)->m_mapBirdFuseTrail[trackid].removeFirst();
                            }
                            ((CustomConfig*)gConfig)->m_mapBirdFuseTrail[trackid].append(QPointF(track.latDegs, track.longDegs));
                        }
                    }
                    else if (topicName == m_topicNameRadarTrack1
                        || topicName == m_topicNameRadarTrack2)
                    {
                        trackid = st.trackId();
                        track.norm.min.id = st.trackId();
                        ((CustomConfig*)gConfig)->m_mapRadarTrack.insert(trackid, track);
                        if (!((CustomConfig*)gConfig)->m_mapRadarTrail[trackid].contains(QPointF(track.latDegs, track.longDegs)))
                        {
                            if (((CustomConfig*)gConfig)->m_mapRadarTrail[trackid].size() > 10)
                            {
                                ((CustomConfig*)gConfig)->m_mapRadarTrail[trackid].removeFirst();
                            }
                            ((CustomConfig*)gConfig)->m_mapRadarTrail[trackid].append(QPointF(track.latDegs, track.longDegs));
                        }

                    }
                    else if (topicName == m_topicNameKuRadarTrack)
                    {
                        ((CustomConfig*)gConfig)->m_mapBirdRadarTrack.insert(trackid, track);
                        if (!((CustomConfig*)gConfig)->m_mapBirdRadarTrail[trackid].contains(QPointF(track.latDegs, track.longDegs)))
                        {
                            if (((CustomConfig*)gConfig)->m_mapBirdRadarTrail[trackid].size() > 10)
                            {
                                ((CustomConfig*)gConfig)->m_mapBirdRadarTrail[trackid].removeFirst();
                            }
                            ((CustomConfig*)gConfig)->m_mapBirdRadarTrail[trackid].append(QPointF(track.latDegs, track.longDegs));
                        }
                    }
                    else if (topicName == m_topicNameBirdRadarTrack
                        || topicName == m_topicNameAutoBirdRadarTrack)
                    {
                        int catid = st.trackCategoryId();
                        if (catid == 3)
                        {
                            track.norm.min.reserved1 = 3;
                        }
                        else
                        {
                            track.norm.min.reserved1 = 1;
                        }
                        track.norm.min.reserved5 = 7;

                        ((CustomConfig*)gConfig)->m_mapBirdRadarTrack.insert(trackid, track);
                        if (!((CustomConfig*)gConfig)->m_mapBirdRadarTrail[trackid].contains(QPointF(track.latDegs, track.longDegs)))
                        {
                            if (((CustomConfig*)gConfig)->m_mapBirdRadarTrail[trackid].size() > 10)
                            {
                                ((CustomConfig*)gConfig)->m_mapBirdRadarTrail[trackid].removeFirst();
                            }
                            ((CustomConfig*)gConfig)->m_mapBirdRadarTrail[trackid].append(QPointF(track.latDegs, track.longDegs));
                        }

                    }
                }
            }
            else
            {
                if (info.valid_data)
                {
                    AISTrack track;
                    track.name = QString::fromStdString(st.trackAlias());
                    track.MMSI = st.mmsi();
                    track.courseDeg = st.course();
                    track.latDeg = st.latitude();
                    track.longDeg = st.longitude();
                    track.speedMps = st.speed();

                    ((CustomConfig*)gConfig)->m_mapAISTrack.insert(track.MMSI, track);
                }
            }
        }
    }
    m_dataMutex.unlock();

}

void TrackClassSubscriberApp::run()
{
    std::unique_lock<std::mutex> lck(terminate_cv_mtx_);
    terminate_cv_.wait(lck, [this]
        {
            return is_stopped();
        });
}

bool TrackClassSubscriberApp::is_stopped()
{
    return stop_.load();
}

void TrackClassSubscriberApp::stop()
{
    stop_.store(true);
    terminate_cv_.notify_all();
}

void TrackClassSubscriberApp::slotClearTrack()
{
    m_dataMutex.lock();
    QWriteLocker trackWriteLocker(&((CustomConfig*)gConfig)->m_trackDataLock);
    QDateTime curTime = QDateTime::currentDateTime();

    //FuseTrack
    auto& fuseTrackMap = ((CustomConfig*)gConfig)->m_mapFuseTrack;
    QList<int> allFuseKeys = fuseTrackMap.keys(); 
    int fuseRemovedCount = 0;

    for (int key : allFuseKeys)
    {
        if (fuseTrackMap.contains(key))
        {
            try
            {
                SPxPacketTrackExtended track = fuseTrackMap.value(key);
                QDateTime time = QDateTime::fromSecsSinceEpoch(static_cast<qint64>(track.msgTimeSecs));
                if (time.secsTo(curTime) > 8)
                {
                    fuseTrackMap.remove(key);
                    fuseRemovedCount++;
                }
            }
            catch (...)
            {
                continue;
            }
        }
    }

    //FuseTrack
    auto& birdfuseTrackMap = ((CustomConfig*)gConfig)->m_mapBirdFuseTrack;
    QList<int> allBirdFuseKeys = birdfuseTrackMap.keys();
    int birdfuseRemovedCount = 0;

    for (int key : allBirdFuseKeys)
    {
        if (birdfuseTrackMap.contains(key))
        {
            try
            {
                SPxPacketTrackExtended track = birdfuseTrackMap.value(key);
                QDateTime time = QDateTime::fromSecsSinceEpoch(static_cast<qint64>(track.msgTimeSecs));
                if (time.secsTo(curTime) > 4)
                {
                    birdfuseTrackMap.remove(key);
                    birdfuseRemovedCount++;
                }
            }
            catch (...)
            {
                continue;
            }
        }
    }

    // ����RadarTrack - ��ȫ��ʹ�õ�����
    auto& radarTrackMap = ((CustomConfig*)gConfig)->m_mapRadarTrack;
    QList<int> allRadarKeys = radarTrackMap.keys(); // ��ȡ���м��ĸ���
    int radarRemovedCount = 0;

    for (int key : allRadarKeys)
    {
        if (radarTrackMap.contains(key)) // �����Ƿ���Ȼ����
        {
            try
            {
                SPxPacketTrackExtended track = radarTrackMap.value(key);
                QDateTime time = QDateTime::fromSecsSinceEpoch(static_cast<qint64>(track.msgTimeSecs));
                if (time.secsTo(curTime) > 8)
                {
                    radarTrackMap.remove(key);
                    radarRemovedCount++;
                }
            }
            catch (...)
            {
                // ������ʳ������������Ԫ��
                continue;
            }
        }
    }

    // ����BirdRadarTrack - ��ȫ��ʹ�õ��������޸�֮ǰ��bug
    auto& radarBirdTrackMap = ((CustomConfig*)gConfig)->m_mapBirdRadarTrack;
    QList<int> allBirdRadarKeys = radarBirdTrackMap.keys(); // ��ȡ���м��ĸ���
    int birdRadarRemovedCount = 0;

    for (int key : allBirdRadarKeys)
    {
        if (radarBirdTrackMap.contains(key)) // �����Ƿ���Ȼ����
        {
            try
            {
                SPxPacketTrackExtended track = radarBirdTrackMap.value(key);
                QDateTime time = QDateTime::fromSecsSinceEpoch(static_cast<qint64>(track.msgTimeSecs));
                if (time.secsTo(curTime) > 8)
                {
                    radarBirdTrackMap.remove(key); // �޸���Ӧ��ɾ��BirdRadarTrack������RadarTrack
                    birdRadarRemovedCount++;
                }
            }
            catch (...)
            {
                // ������ʳ������������Ԫ��
                continue;
            }
        }
    }

    //qDebug() << "=======================clear track, removed" << fuseRemovedCount << "fuse tracks," << radarRemovedCount << "radar tracks," << birdRadarRemovedCount << "bird radar tracks";
    m_dataMutex.unlock();
}