// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TrackClassTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "TrackClassTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "TrackClass.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_TrackDataClass_type_identifier(
        TypeIdentifierPair& type_ids_TrackDataClass)
{

    ReturnCode_t return_code_TrackDataClass {eprosima::fastdds::dds::RETCODE_OK};
    return_code_TrackDataClass =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "TrackDataClass", type_ids_TrackDataClass);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_TrackDataClass)
    {
        StructTypeFlag struct_flags_TrackDataClass = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_TrackDataClass = "TrackDataClass";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_TrackDataClass;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_TrackDataClass;
        CompleteTypeDetail detail_TrackDataClass = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_TrackDataClass, ann_custom_TrackDataClass, type_name_TrackDataClass.to_string());
        CompleteStructHeader header_TrackDataClass;
        header_TrackDataClass = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_TrackDataClass);
        CompleteStructMemberSeq member_seq_TrackDataClass;
        {
            TypeIdentifierPair type_ids_trackId;
            ReturnCode_t return_code_trackId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_trackId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_trackId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_trackId)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "trackId Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_trackId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_trackId = 0x00000000;
            bool common_trackId_ec {false};
            CommonStructMember common_trackId {TypeObjectUtils::build_common_struct_member(member_id_trackId, member_flags_trackId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_trackId, common_trackId_ec))};
            if (!common_trackId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure trackId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_trackId = "trackId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_trackId;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_trackId = TypeObjectUtils::build_complete_member_detail(name_trackId, member_ann_builtin_trackId, ann_custom_TrackDataClass);
            CompleteStructMember member_trackId = TypeObjectUtils::build_complete_struct_member(common_trackId, detail_trackId);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_trackId);
        }
        {
            TypeIdentifierPair type_ids_mmsi;
            ReturnCode_t return_code_mmsi {eprosima::fastdds::dds::RETCODE_OK};
            return_code_mmsi =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_mmsi);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_mmsi)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "mmsi Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_mmsi = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_mmsi = 0x00000001;
            bool common_mmsi_ec {false};
            CommonStructMember common_mmsi {TypeObjectUtils::build_common_struct_member(member_id_mmsi, member_flags_mmsi, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_mmsi, common_mmsi_ec))};
            if (!common_mmsi_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure mmsi member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_mmsi = "mmsi";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_mmsi;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_mmsi = TypeObjectUtils::build_complete_member_detail(name_mmsi, member_ann_builtin_mmsi, ann_custom_TrackDataClass);
            CompleteStructMember member_mmsi = TypeObjectUtils::build_complete_struct_member(common_mmsi, detail_mmsi);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_mmsi);
        }
        {
            TypeIdentifierPair type_ids_uniqueId;
            ReturnCode_t return_code_uniqueId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_uniqueId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_uniqueId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_uniqueId)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "uniqueId Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_uniqueId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_uniqueId = 0x00000002;
            bool common_uniqueId_ec {false};
            CommonStructMember common_uniqueId {TypeObjectUtils::build_common_struct_member(member_id_uniqueId, member_flags_uniqueId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_uniqueId, common_uniqueId_ec))};
            if (!common_uniqueId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure uniqueId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_uniqueId = "uniqueId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_uniqueId;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_uniqueId = TypeObjectUtils::build_complete_member_detail(name_uniqueId, member_ann_builtin_uniqueId, ann_custom_TrackDataClass);
            CompleteStructMember member_uniqueId = TypeObjectUtils::build_complete_struct_member(common_uniqueId, detail_uniqueId);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_uniqueId);
        }
        {
            TypeIdentifierPair type_ids_longitude;
            ReturnCode_t return_code_longitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_longitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_longitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_longitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "longitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_longitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_longitude = 0x00000003;
            bool common_longitude_ec {false};
            CommonStructMember common_longitude {TypeObjectUtils::build_common_struct_member(member_id_longitude, member_flags_longitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_longitude, common_longitude_ec))};
            if (!common_longitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure longitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_longitude = "longitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_longitude;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_longitude = TypeObjectUtils::build_complete_member_detail(name_longitude, member_ann_builtin_longitude, ann_custom_TrackDataClass);
            CompleteStructMember member_longitude = TypeObjectUtils::build_complete_struct_member(common_longitude, detail_longitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_longitude);
        }
        {
            TypeIdentifierPair type_ids_latitude;
            ReturnCode_t return_code_latitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_latitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_latitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_latitude)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "latitude Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_latitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_latitude = 0x00000004;
            bool common_latitude_ec {false};
            CommonStructMember common_latitude {TypeObjectUtils::build_common_struct_member(member_id_latitude, member_flags_latitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_latitude, common_latitude_ec))};
            if (!common_latitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure latitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_latitude = "latitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_latitude;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_latitude = TypeObjectUtils::build_complete_member_detail(name_latitude, member_ann_builtin_latitude, ann_custom_TrackDataClass);
            CompleteStructMember member_latitude = TypeObjectUtils::build_complete_struct_member(common_latitude, detail_latitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_latitude);
        }
        {
            TypeIdentifierPair type_ids_course;
            ReturnCode_t return_code_course {eprosima::fastdds::dds::RETCODE_OK};
            return_code_course =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_course);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_course)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "course Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_course = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_course = 0x00000005;
            bool common_course_ec {false};
            CommonStructMember common_course {TypeObjectUtils::build_common_struct_member(member_id_course, member_flags_course, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_course, common_course_ec))};
            if (!common_course_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure course member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_course = "course";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_course;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_course = TypeObjectUtils::build_complete_member_detail(name_course, member_ann_builtin_course, ann_custom_TrackDataClass);
            CompleteStructMember member_course = TypeObjectUtils::build_complete_struct_member(common_course, detail_course);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_course);
        }
        {
            TypeIdentifierPair type_ids_distance;
            ReturnCode_t return_code_distance {eprosima::fastdds::dds::RETCODE_OK};
            return_code_distance =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_distance);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_distance)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "distance Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_distance = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_distance = 0x00000006;
            bool common_distance_ec {false};
            CommonStructMember common_distance {TypeObjectUtils::build_common_struct_member(member_id_distance, member_flags_distance, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_distance, common_distance_ec))};
            if (!common_distance_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure distance member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_distance = "distance";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_distance;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_distance = TypeObjectUtils::build_complete_member_detail(name_distance, member_ann_builtin_distance, ann_custom_TrackDataClass);
            CompleteStructMember member_distance = TypeObjectUtils::build_complete_struct_member(common_distance, detail_distance);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_distance);
        }
        {
            TypeIdentifierPair type_ids_speed;
            ReturnCode_t return_code_speed {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_speed);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "speed Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_speed = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed = 0x00000007;
            bool common_speed_ec {false};
            CommonStructMember common_speed {TypeObjectUtils::build_common_struct_member(member_id_speed, member_flags_speed, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed, common_speed_ec))};
            if (!common_speed_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed = "speed";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_speed = TypeObjectUtils::build_complete_member_detail(name_speed, member_ann_builtin_speed, ann_custom_TrackDataClass);
            CompleteStructMember member_speed = TypeObjectUtils::build_complete_struct_member(common_speed, detail_speed);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_speed);
        }
        {
            TypeIdentifierPair type_ids_speed_N;
            ReturnCode_t return_code_speed_N {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed_N =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_speed_N);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed_N)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "speed_N Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_speed_N = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed_N = 0x00000008;
            bool common_speed_N_ec {false};
            CommonStructMember common_speed_N {TypeObjectUtils::build_common_struct_member(member_id_speed_N, member_flags_speed_N, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed_N, common_speed_N_ec))};
            if (!common_speed_N_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed_N member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed_N = "speed_N";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed_N;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_speed_N = TypeObjectUtils::build_complete_member_detail(name_speed_N, member_ann_builtin_speed_N, ann_custom_TrackDataClass);
            CompleteStructMember member_speed_N = TypeObjectUtils::build_complete_struct_member(common_speed_N, detail_speed_N);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_speed_N);
        }
        {
            TypeIdentifierPair type_ids_speed__E;
            ReturnCode_t return_code_speed__E {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed__E =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_speed__E);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed__E)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "speed__E Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_speed__E = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed__E = 0x00000009;
            bool common_speed__E_ec {false};
            CommonStructMember common_speed__E {TypeObjectUtils::build_common_struct_member(member_id_speed__E, member_flags_speed__E, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed__E, common_speed__E_ec))};
            if (!common_speed__E_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed__E member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed__E = "speed__E";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed__E;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_speed__E = TypeObjectUtils::build_complete_member_detail(name_speed__E, member_ann_builtin_speed__E, ann_custom_TrackDataClass);
            CompleteStructMember member_speed__E = TypeObjectUtils::build_complete_struct_member(common_speed__E, detail_speed__E);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_speed__E);
        }
        {
            TypeIdentifierPair type_ids_speed_V;
            ReturnCode_t return_code_speed_V {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed_V =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_speed_V);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed_V)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "speed_V Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_speed_V = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed_V = 0x0000000a;
            bool common_speed_V_ec {false};
            CommonStructMember common_speed_V {TypeObjectUtils::build_common_struct_member(member_id_speed_V, member_flags_speed_V, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed_V, common_speed_V_ec))};
            if (!common_speed_V_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed_V member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed_V = "speed_V";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed_V;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_speed_V = TypeObjectUtils::build_complete_member_detail(name_speed_V, member_ann_builtin_speed_V, ann_custom_TrackDataClass);
            CompleteStructMember member_speed_V = TypeObjectUtils::build_complete_struct_member(common_speed_V, detail_speed_V);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_speed_V);
        }
        {
            TypeIdentifierPair type_ids_height;
            ReturnCode_t return_code_height {eprosima::fastdds::dds::RETCODE_OK};
            return_code_height =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_height);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_height)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "height Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_height = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_height = 0x0000000b;
            bool common_height_ec {false};
            CommonStructMember common_height {TypeObjectUtils::build_common_struct_member(member_id_height, member_flags_height, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_height, common_height_ec))};
            if (!common_height_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure height member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_height = "height";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_height;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_height = TypeObjectUtils::build_complete_member_detail(name_height, member_ann_builtin_height, ann_custom_TrackDataClass);
            CompleteStructMember member_height = TypeObjectUtils::build_complete_struct_member(common_height, detail_height);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_height);
        }
        {
            TypeIdentifierPair type_ids_azimuth;
            ReturnCode_t return_code_azimuth {eprosima::fastdds::dds::RETCODE_OK};
            return_code_azimuth =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_azimuth);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_azimuth)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "azimuth Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_azimuth = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_azimuth = 0x0000000c;
            bool common_azimuth_ec {false};
            CommonStructMember common_azimuth {TypeObjectUtils::build_common_struct_member(member_id_azimuth, member_flags_azimuth, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_azimuth, common_azimuth_ec))};
            if (!common_azimuth_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure azimuth member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_azimuth = "azimuth";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_azimuth;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_azimuth = TypeObjectUtils::build_complete_member_detail(name_azimuth, member_ann_builtin_azimuth, ann_custom_TrackDataClass);
            CompleteStructMember member_azimuth = TypeObjectUtils::build_complete_struct_member(common_azimuth, detail_azimuth);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_azimuth);
        }
        {
            TypeIdentifierPair type_ids_range;
            ReturnCode_t return_code_range {eprosima::fastdds::dds::RETCODE_OK};
            return_code_range =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_range);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_range)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "range Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_range = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_range = 0x0000000d;
            bool common_range_ec {false};
            CommonStructMember common_range {TypeObjectUtils::build_common_struct_member(member_id_range, member_flags_range, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_range, common_range_ec))};
            if (!common_range_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure range member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_range = "range";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_range;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_range = TypeObjectUtils::build_complete_member_detail(name_range, member_ann_builtin_range, ann_custom_TrackDataClass);
            CompleteStructMember member_range = TypeObjectUtils::build_complete_struct_member(common_range, detail_range);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_range);
        }
        {
            TypeIdentifierPair type_ids_sizeMetres;
            ReturnCode_t return_code_sizeMetres {eprosima::fastdds::dds::RETCODE_OK};
            return_code_sizeMetres =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_sizeMetres);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_sizeMetres)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "sizeMetres Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_sizeMetres = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_sizeMetres = 0x0000000e;
            bool common_sizeMetres_ec {false};
            CommonStructMember common_sizeMetres {TypeObjectUtils::build_common_struct_member(member_id_sizeMetres, member_flags_sizeMetres, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_sizeMetres, common_sizeMetres_ec))};
            if (!common_sizeMetres_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure sizeMetres member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_sizeMetres = "sizeMetres";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_sizeMetres;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_sizeMetres = TypeObjectUtils::build_complete_member_detail(name_sizeMetres, member_ann_builtin_sizeMetres, ann_custom_TrackDataClass);
            CompleteStructMember member_sizeMetres = TypeObjectUtils::build_complete_struct_member(common_sizeMetres, detail_sizeMetres);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_sizeMetres);
        }
        {
            TypeIdentifierPair type_ids_sizeDegrees;
            ReturnCode_t return_code_sizeDegrees {eprosima::fastdds::dds::RETCODE_OK};
            return_code_sizeDegrees =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_sizeDegrees);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_sizeDegrees)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "sizeDegrees Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_sizeDegrees = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_sizeDegrees = 0x0000000f;
            bool common_sizeDegrees_ec {false};
            CommonStructMember common_sizeDegrees {TypeObjectUtils::build_common_struct_member(member_id_sizeDegrees, member_flags_sizeDegrees, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_sizeDegrees, common_sizeDegrees_ec))};
            if (!common_sizeDegrees_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure sizeDegrees member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_sizeDegrees = "sizeDegrees";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_sizeDegrees;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_sizeDegrees = TypeObjectUtils::build_complete_member_detail(name_sizeDegrees, member_ann_builtin_sizeDegrees, ann_custom_TrackDataClass);
            CompleteStructMember member_sizeDegrees = TypeObjectUtils::build_complete_struct_member(common_sizeDegrees, detail_sizeDegrees);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_sizeDegrees);
        }
        {
            TypeIdentifierPair type_ids_radarId;
            ReturnCode_t return_code_radarId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_radarId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_radarId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_radarId)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_radarId))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_radarId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_radarId = 0x00000010;
            bool common_radarId_ec {false};
            CommonStructMember common_radarId {TypeObjectUtils::build_common_struct_member(member_id_radarId, member_flags_radarId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_radarId, common_radarId_ec))};
            if (!common_radarId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure radarId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_radarId = "radarId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_radarId;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_radarId = TypeObjectUtils::build_complete_member_detail(name_radarId, member_ann_builtin_radarId, ann_custom_TrackDataClass);
            CompleteStructMember member_radarId = TypeObjectUtils::build_complete_struct_member(common_radarId, detail_radarId);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_radarId);
        }
        {
            TypeIdentifierPair type_ids_dotID;
            ReturnCode_t return_code_dotID {eprosima::fastdds::dds::RETCODE_OK};
            return_code_dotID =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_dotID);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_dotID)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "dotID Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_dotID = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_dotID = 0x00000011;
            bool common_dotID_ec {false};
            CommonStructMember common_dotID {TypeObjectUtils::build_common_struct_member(member_id_dotID, member_flags_dotID, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_dotID, common_dotID_ec))};
            if (!common_dotID_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure dotID member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_dotID = "dotID";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_dotID;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_dotID = TypeObjectUtils::build_complete_member_detail(name_dotID, member_ann_builtin_dotID, ann_custom_TrackDataClass);
            CompleteStructMember member_dotID = TypeObjectUtils::build_complete_struct_member(common_dotID, detail_dotID);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_dotID);
        }
        {
            TypeIdentifierPair type_ids_trackQuality;
            ReturnCode_t return_code_trackQuality {eprosima::fastdds::dds::RETCODE_OK};
            return_code_trackQuality =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_trackQuality);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_trackQuality)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "trackQuality Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_trackQuality = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_trackQuality = 0x00000012;
            bool common_trackQuality_ec {false};
            CommonStructMember common_trackQuality {TypeObjectUtils::build_common_struct_member(member_id_trackQuality, member_flags_trackQuality, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_trackQuality, common_trackQuality_ec))};
            if (!common_trackQuality_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure trackQuality member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_trackQuality = "trackQuality";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_trackQuality;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_trackQuality = TypeObjectUtils::build_complete_member_detail(name_trackQuality, member_ann_builtin_trackQuality, ann_custom_TrackDataClass);
            CompleteStructMember member_trackQuality = TypeObjectUtils::build_complete_struct_member(common_trackQuality, detail_trackQuality);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_trackQuality);
        }
        {
            TypeIdentifierPair type_ids_fusion;
            ReturnCode_t return_code_fusion {eprosima::fastdds::dds::RETCODE_OK};
            return_code_fusion =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_fusion);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_fusion)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "fusion Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_fusion = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_fusion = 0x00000013;
            bool common_fusion_ec {false};
            CommonStructMember common_fusion {TypeObjectUtils::build_common_struct_member(member_id_fusion, member_flags_fusion, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_fusion, common_fusion_ec))};
            if (!common_fusion_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure fusion member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_fusion = "fusion";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_fusion;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_fusion = TypeObjectUtils::build_complete_member_detail(name_fusion, member_ann_builtin_fusion, ann_custom_TrackDataClass);
            CompleteStructMember member_fusion = TypeObjectUtils::build_complete_struct_member(common_fusion, detail_fusion);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_fusion);
        }
        {
            TypeIdentifierPair type_ids_sensors;
            ReturnCode_t return_code_sensors {eprosima::fastdds::dds::RETCODE_OK};
            return_code_sensors =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_sensors);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_sensors)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "sensors Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_sensors = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_sensors = 0x00000014;
            bool common_sensors_ec {false};
            CommonStructMember common_sensors {TypeObjectUtils::build_common_struct_member(member_id_sensors, member_flags_sensors, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_sensors, common_sensors_ec))};
            if (!common_sensors_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure sensors member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_sensors = "sensors";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_sensors;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_sensors = TypeObjectUtils::build_complete_member_detail(name_sensors, member_ann_builtin_sensors, ann_custom_TrackDataClass);
            CompleteStructMember member_sensors = TypeObjectUtils::build_complete_struct_member(common_sensors, detail_sensors);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_sensors);
        }
        {
            TypeIdentifierPair type_ids_trackID;
            ReturnCode_t return_code_trackID {eprosima::fastdds::dds::RETCODE_OK};
            return_code_trackID =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_uint32_t_8", type_ids_trackID);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_trackID)
            {
                return_code_trackID =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_uint32_t", type_ids_trackID);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_trackID)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_uint32_t_8_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_uint32_t_8 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_trackID, element_identifier_anonymous_array_uint32_t_8_ec))};
                if (!element_identifier_anonymous_array_uint32_t_8_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_uint32_t_8 = EK_COMPLETE;
                if (TK_NONE == type_ids_trackID.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_uint32_t_8 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_uint32_t_8 = 0;
                PlainCollectionHeader header_anonymous_array_uint32_t_8 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_uint32_t_8, element_flags_anonymous_array_uint32_t_8);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(8));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_uint32_t_8, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_uint32_t_8));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_uint32_t_8", type_ids_trackID))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_uint32_t_8 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_trackID = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_trackID = 0x00000015;
            bool common_trackID_ec {false};
            CommonStructMember common_trackID {TypeObjectUtils::build_common_struct_member(member_id_trackID, member_flags_trackID, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_trackID, common_trackID_ec))};
            if (!common_trackID_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure trackID member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_trackID = "trackID";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_trackID;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_trackID = TypeObjectUtils::build_complete_member_detail(name_trackID, member_ann_builtin_trackID, ann_custom_TrackDataClass);
            CompleteStructMember member_trackID = TypeObjectUtils::build_complete_struct_member(common_trackID, detail_trackID);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_trackID);
        }
        {
            TypeIdentifierPair type_ids_timeStamp;
            ReturnCode_t return_code_timeStamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timeStamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_timeStamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timeStamp)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timeStamp Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timeStamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timeStamp = 0x00000016;
            bool common_timeStamp_ec {false};
            CommonStructMember common_timeStamp {TypeObjectUtils::build_common_struct_member(member_id_timeStamp, member_flags_timeStamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timeStamp, common_timeStamp_ec))};
            if (!common_timeStamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timeStamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timeStamp = "timeStamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timeStamp;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_timeStamp = TypeObjectUtils::build_complete_member_detail(name_timeStamp, member_ann_builtin_timeStamp, ann_custom_TrackDataClass);
            CompleteStructMember member_timeStamp = TypeObjectUtils::build_complete_struct_member(common_timeStamp, detail_timeStamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_timeStamp);
        }
        {
            TypeIdentifierPair type_ids_threatScore;
            ReturnCode_t return_code_threatScore {eprosima::fastdds::dds::RETCODE_OK};
            return_code_threatScore =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_threatScore);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_threatScore)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "threatScore Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_threatScore = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_threatScore = 0x00000017;
            bool common_threatScore_ec {false};
            CommonStructMember common_threatScore {TypeObjectUtils::build_common_struct_member(member_id_threatScore, member_flags_threatScore, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_threatScore, common_threatScore_ec))};
            if (!common_threatScore_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure threatScore member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_threatScore = "threatScore";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_threatScore;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_threatScore = TypeObjectUtils::build_complete_member_detail(name_threatScore, member_ann_builtin_threatScore, ann_custom_TrackDataClass);
            CompleteStructMember member_threatScore = TypeObjectUtils::build_complete_struct_member(common_threatScore, detail_threatScore);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_threatScore);
        }
        {
            TypeIdentifierPair type_ids_threatLevel;
            ReturnCode_t return_code_threatLevel {eprosima::fastdds::dds::RETCODE_OK};
            return_code_threatLevel =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_threatLevel);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_threatLevel)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "threatLevel Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_threatLevel = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_threatLevel = 0x00000018;
            bool common_threatLevel_ec {false};
            CommonStructMember common_threatLevel {TypeObjectUtils::build_common_struct_member(member_id_threatLevel, member_flags_threatLevel, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_threatLevel, common_threatLevel_ec))};
            if (!common_threatLevel_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure threatLevel member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_threatLevel = "threatLevel";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_threatLevel;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_threatLevel = TypeObjectUtils::build_complete_member_detail(name_threatLevel, member_ann_builtin_threatLevel, ann_custom_TrackDataClass);
            CompleteStructMember member_threatLevel = TypeObjectUtils::build_complete_struct_member(common_threatLevel, detail_threatLevel);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_threatLevel);
        }
        {
            TypeIdentifierPair type_ids_trackCategoryId;
            ReturnCode_t return_code_trackCategoryId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_trackCategoryId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_trackCategoryId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_trackCategoryId)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "trackCategoryId Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_trackCategoryId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_trackCategoryId = 0x00000019;
            bool common_trackCategoryId_ec {false};
            CommonStructMember common_trackCategoryId {TypeObjectUtils::build_common_struct_member(member_id_trackCategoryId, member_flags_trackCategoryId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_trackCategoryId, common_trackCategoryId_ec))};
            if (!common_trackCategoryId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure trackCategoryId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_trackCategoryId = "trackCategoryId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_trackCategoryId;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_trackCategoryId = TypeObjectUtils::build_complete_member_detail(name_trackCategoryId, member_ann_builtin_trackCategoryId, ann_custom_TrackDataClass);
            CompleteStructMember member_trackCategoryId = TypeObjectUtils::build_complete_struct_member(common_trackCategoryId, detail_trackCategoryId);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_trackCategoryId);
        }
        {
            TypeIdentifierPair type_ids_trackCategoryName;
            ReturnCode_t return_code_trackCategoryName {eprosima::fastdds::dds::RETCODE_OK};
            return_code_trackCategoryName =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_trackCategoryName);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_trackCategoryName)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_trackCategoryName))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_trackCategoryName = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_trackCategoryName = 0x0000001a;
            bool common_trackCategoryName_ec {false};
            CommonStructMember common_trackCategoryName {TypeObjectUtils::build_common_struct_member(member_id_trackCategoryName, member_flags_trackCategoryName, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_trackCategoryName, common_trackCategoryName_ec))};
            if (!common_trackCategoryName_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure trackCategoryName member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_trackCategoryName = "trackCategoryName";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_trackCategoryName;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_trackCategoryName = TypeObjectUtils::build_complete_member_detail(name_trackCategoryName, member_ann_builtin_trackCategoryName, ann_custom_TrackDataClass);
            CompleteStructMember member_trackCategoryName = TypeObjectUtils::build_complete_struct_member(common_trackCategoryName, detail_trackCategoryName);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_trackCategoryName);
        }
        {
            TypeIdentifierPair type_ids_trackAlias;
            ReturnCode_t return_code_trackAlias {eprosima::fastdds::dds::RETCODE_OK};
            return_code_trackAlias =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_trackAlias);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_trackAlias)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_trackAlias))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_trackAlias = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_trackAlias = 0x0000001b;
            bool common_trackAlias_ec {false};
            CommonStructMember common_trackAlias {TypeObjectUtils::build_common_struct_member(member_id_trackAlias, member_flags_trackAlias, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_trackAlias, common_trackAlias_ec))};
            if (!common_trackAlias_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure trackAlias member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_trackAlias = "trackAlias";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_trackAlias;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_trackAlias = TypeObjectUtils::build_complete_member_detail(name_trackAlias, member_ann_builtin_trackAlias, ann_custom_TrackDataClass);
            CompleteStructMember member_trackAlias = TypeObjectUtils::build_complete_struct_member(common_trackAlias, detail_trackAlias);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_trackAlias);
        }
        {
            TypeIdentifierPair type_ids_isManual;
            ReturnCode_t return_code_isManual {eprosima::fastdds::dds::RETCODE_OK};
            return_code_isManual =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_isManual);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_isManual)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "isManual Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_isManual = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_isManual = 0x0000001c;
            bool common_isManual_ec {false};
            CommonStructMember common_isManual {TypeObjectUtils::build_common_struct_member(member_id_isManual, member_flags_isManual, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_isManual, common_isManual_ec))};
            if (!common_isManual_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure isManual member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_isManual = "isManual";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_isManual;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_isManual = TypeObjectUtils::build_complete_member_detail(name_isManual, member_ann_builtin_isManual, ann_custom_TrackDataClass);
            CompleteStructMember member_isManual = TypeObjectUtils::build_complete_struct_member(common_isManual, detail_isManual);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_isManual);
        }
        {
            TypeIdentifierPair type_ids_modifiedBy;
            ReturnCode_t return_code_modifiedBy {eprosima::fastdds::dds::RETCODE_OK};
            return_code_modifiedBy =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_modifiedBy);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_modifiedBy)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_modifiedBy))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_modifiedBy = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_modifiedBy = 0x0000001d;
            bool common_modifiedBy_ec {false};
            CommonStructMember common_modifiedBy {TypeObjectUtils::build_common_struct_member(member_id_modifiedBy, member_flags_modifiedBy, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_modifiedBy, common_modifiedBy_ec))};
            if (!common_modifiedBy_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure modifiedBy member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_modifiedBy = "modifiedBy";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_modifiedBy;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_modifiedBy = TypeObjectUtils::build_complete_member_detail(name_modifiedBy, member_ann_builtin_modifiedBy, ann_custom_TrackDataClass);
            CompleteStructMember member_modifiedBy = TypeObjectUtils::build_complete_struct_member(common_modifiedBy, detail_modifiedBy);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_modifiedBy);
        }
        {
            TypeIdentifierPair type_ids_modifiedTime;
            ReturnCode_t return_code_modifiedTime {eprosima::fastdds::dds::RETCODE_OK};
            return_code_modifiedTime =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_modifiedTime);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_modifiedTime)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "modifiedTime Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_modifiedTime = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_modifiedTime = 0x0000001e;
            bool common_modifiedTime_ec {false};
            CommonStructMember common_modifiedTime {TypeObjectUtils::build_common_struct_member(member_id_modifiedTime, member_flags_modifiedTime, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_modifiedTime, common_modifiedTime_ec))};
            if (!common_modifiedTime_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure modifiedTime member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_modifiedTime = "modifiedTime";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_modifiedTime;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_modifiedTime = TypeObjectUtils::build_complete_member_detail(name_modifiedTime, member_ann_builtin_modifiedTime, ann_custom_TrackDataClass);
            CompleteStructMember member_modifiedTime = TypeObjectUtils::build_complete_struct_member(common_modifiedTime, detail_modifiedTime);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_modifiedTime);
        }
        {
            TypeIdentifierPair type_ids_reserved0;
            ReturnCode_t return_code_reserved0 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_reserved0 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_reserved0);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_reserved0)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "reserved0 Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_reserved0 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_reserved0 = 0x0000001f;
            bool common_reserved0_ec {false};
            CommonStructMember common_reserved0 {TypeObjectUtils::build_common_struct_member(member_id_reserved0, member_flags_reserved0, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_reserved0, common_reserved0_ec))};
            if (!common_reserved0_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure reserved0 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_reserved0 = "reserved0";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_reserved0;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_reserved0 = TypeObjectUtils::build_complete_member_detail(name_reserved0, member_ann_builtin_reserved0, ann_custom_TrackDataClass);
            CompleteStructMember member_reserved0 = TypeObjectUtils::build_complete_struct_member(common_reserved0, detail_reserved0);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_reserved0);
        }
        {
            TypeIdentifierPair type_ids_reserved1;
            ReturnCode_t return_code_reserved1 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_reserved1 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_reserved1);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_reserved1)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "reserved1 Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_reserved1 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_reserved1 = 0x00000020;
            bool common_reserved1_ec {false};
            CommonStructMember common_reserved1 {TypeObjectUtils::build_common_struct_member(member_id_reserved1, member_flags_reserved1, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_reserved1, common_reserved1_ec))};
            if (!common_reserved1_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure reserved1 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_reserved1 = "reserved1";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_reserved1;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_reserved1 = TypeObjectUtils::build_complete_member_detail(name_reserved1, member_ann_builtin_reserved1, ann_custom_TrackDataClass);
            CompleteStructMember member_reserved1 = TypeObjectUtils::build_complete_struct_member(common_reserved1, detail_reserved1);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_reserved1);
        }
        {
            TypeIdentifierPair type_ids_reserved2;
            ReturnCode_t return_code_reserved2 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_reserved2 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_reserved2);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_reserved2)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "reserved2 Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_reserved2 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_reserved2 = 0x00000021;
            bool common_reserved2_ec {false};
            CommonStructMember common_reserved2 {TypeObjectUtils::build_common_struct_member(member_id_reserved2, member_flags_reserved2, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_reserved2, common_reserved2_ec))};
            if (!common_reserved2_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure reserved2 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_reserved2 = "reserved2";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_reserved2;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_reserved2 = TypeObjectUtils::build_complete_member_detail(name_reserved2, member_ann_builtin_reserved2, ann_custom_TrackDataClass);
            CompleteStructMember member_reserved2 = TypeObjectUtils::build_complete_struct_member(common_reserved2, detail_reserved2);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_reserved2);
        }
        {
            TypeIdentifierPair type_ids_reserved3;
            ReturnCode_t return_code_reserved3 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_reserved3 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_reserved3);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_reserved3)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "reserved3 Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_reserved3 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_reserved3 = 0x00000022;
            bool common_reserved3_ec {false};
            CommonStructMember common_reserved3 {TypeObjectUtils::build_common_struct_member(member_id_reserved3, member_flags_reserved3, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_reserved3, common_reserved3_ec))};
            if (!common_reserved3_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure reserved3 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_reserved3 = "reserved3";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_reserved3;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_reserved3 = TypeObjectUtils::build_complete_member_detail(name_reserved3, member_ann_builtin_reserved3, ann_custom_TrackDataClass);
            CompleteStructMember member_reserved3 = TypeObjectUtils::build_complete_struct_member(common_reserved3, detail_reserved3);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_reserved3);
        }
        {
            TypeIdentifierPair type_ids_reserved4;
            ReturnCode_t return_code_reserved4 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_reserved4 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_reserved4);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_reserved4)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "reserved4 Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_reserved4 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_reserved4 = 0x00000023;
            bool common_reserved4_ec {false};
            CommonStructMember common_reserved4 {TypeObjectUtils::build_common_struct_member(member_id_reserved4, member_flags_reserved4, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_reserved4, common_reserved4_ec))};
            if (!common_reserved4_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure reserved4 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_reserved4 = "reserved4";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_reserved4;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_reserved4 = TypeObjectUtils::build_complete_member_detail(name_reserved4, member_ann_builtin_reserved4, ann_custom_TrackDataClass);
            CompleteStructMember member_reserved4 = TypeObjectUtils::build_complete_struct_member(common_reserved4, detail_reserved4);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_reserved4);
        }
        {
            TypeIdentifierPair type_ids_reserved5;
            ReturnCode_t return_code_reserved5 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_reserved5 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_reserved5);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_reserved5)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "reserved5 Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_reserved5 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_reserved5 = 0x00000024;
            bool common_reserved5_ec {false};
            CommonStructMember common_reserved5 {TypeObjectUtils::build_common_struct_member(member_id_reserved5, member_flags_reserved5, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_reserved5, common_reserved5_ec))};
            if (!common_reserved5_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure reserved5 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_reserved5 = "reserved5";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_reserved5;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_reserved5 = TypeObjectUtils::build_complete_member_detail(name_reserved5, member_ann_builtin_reserved5, ann_custom_TrackDataClass);
            CompleteStructMember member_reserved5 = TypeObjectUtils::build_complete_struct_member(common_reserved5, detail_reserved5);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_reserved5);
        }
        {
            TypeIdentifierPair type_ids_reserved6;
            ReturnCode_t return_code_reserved6 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_reserved6 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_reserved6);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_reserved6)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_reserved6))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_reserved6 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_reserved6 = 0x00000025;
            bool common_reserved6_ec {false};
            CommonStructMember common_reserved6 {TypeObjectUtils::build_common_struct_member(member_id_reserved6, member_flags_reserved6, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_reserved6, common_reserved6_ec))};
            if (!common_reserved6_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure reserved6 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_reserved6 = "reserved6";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_reserved6;
            ann_custom_TrackDataClass.reset();
            CompleteMemberDetail detail_reserved6 = TypeObjectUtils::build_complete_member_detail(name_reserved6, member_ann_builtin_reserved6, ann_custom_TrackDataClass);
            CompleteStructMember member_reserved6 = TypeObjectUtils::build_complete_struct_member(common_reserved6, detail_reserved6);
            TypeObjectUtils::add_complete_struct_member(member_seq_TrackDataClass, member_reserved6);
        }
        CompleteStructType struct_type_TrackDataClass = TypeObjectUtils::build_complete_struct_type(struct_flags_TrackDataClass, header_TrackDataClass, member_seq_TrackDataClass);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_TrackDataClass, type_name_TrackDataClass.to_string(), type_ids_TrackDataClass))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "TrackDataClass already registered in TypeObjectRegistry for a different type.");
        }
    }
}

