// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TrackClass.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__TRACKCLASS_HPP
#define FAST_DDS_GENERATED__TRACKCLASS_HPP

#include <array>
#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TRACKCLASS_SOURCE)
#define TRACKCLASS_DllAPI __declspec( dllexport )
#else
#define TRACKCLASS_DllAPI __declspec( dllimport )
#endif // TRACKCLASS_SOURCE
#else
#define TRACKCLASS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TRACKCLASS_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure TrackDataClass defined by the user in the IDL file.
 * @ingroup TrackClass
 */
class TrackDataClass
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TrackDataClass()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TrackDataClass()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object TrackDataClass that will be copied.
     */
    eProsima_user_DllExport TrackDataClass(
            const TrackDataClass& x)
    {
                    m_trackId = x.m_trackId;

                    m_mmsi = x.m_mmsi;

                    m_uniqueId = x.m_uniqueId;

                    m_longitude = x.m_longitude;

                    m_latitude = x.m_latitude;

                    m_course = x.m_course;

                    m_distance = x.m_distance;

                    m_speed = x.m_speed;

                    m_speed_N = x.m_speed_N;

                    m_speed__E = x.m_speed__E;

                    m_speed_V = x.m_speed_V;

                    m_height = x.m_height;

                    m_azimuth = x.m_azimuth;

                    m_range = x.m_range;

                    m_sizeMetres = x.m_sizeMetres;

                    m_sizeDegrees = x.m_sizeDegrees;

                    m_radarId = x.m_radarId;

                    m_dotID = x.m_dotID;

                    m_trackQuality = x.m_trackQuality;

                    m_fusion = x.m_fusion;

                    m_sensors = x.m_sensors;

                    m_trackID = x.m_trackID;

                    m_timeStamp = x.m_timeStamp;

                    m_threatScore = x.m_threatScore;

                    m_threatLevel = x.m_threatLevel;

                    m_trackCategoryId = x.m_trackCategoryId;

                    m_trackCategoryName = x.m_trackCategoryName;

                    m_trackAlias = x.m_trackAlias;

                    m_isManual = x.m_isManual;

                    m_modifiedBy = x.m_modifiedBy;

                    m_modifiedTime = x.m_modifiedTime;

                    m_reserved0 = x.m_reserved0;

                    m_reserved1 = x.m_reserved1;

                    m_reserved2 = x.m_reserved2;

                    m_reserved3 = x.m_reserved3;

                    m_reserved4 = x.m_reserved4;

                    m_reserved5 = x.m_reserved5;

                    m_reserved6 = x.m_reserved6;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object TrackDataClass that will be copied.
     */
    eProsima_user_DllExport TrackDataClass(
            TrackDataClass&& x) noexcept
    {
        m_trackId = x.m_trackId;
        m_mmsi = x.m_mmsi;
        m_uniqueId = x.m_uniqueId;
        m_longitude = x.m_longitude;
        m_latitude = x.m_latitude;
        m_course = x.m_course;
        m_distance = x.m_distance;
        m_speed = x.m_speed;
        m_speed_N = x.m_speed_N;
        m_speed__E = x.m_speed__E;
        m_speed_V = x.m_speed_V;
        m_height = x.m_height;
        m_azimuth = x.m_azimuth;
        m_range = x.m_range;
        m_sizeMetres = x.m_sizeMetres;
        m_sizeDegrees = x.m_sizeDegrees;
        m_radarId = std::move(x.m_radarId);
        m_dotID = x.m_dotID;
        m_trackQuality = x.m_trackQuality;
        m_fusion = x.m_fusion;
        m_sensors = x.m_sensors;
        m_trackID = std::move(x.m_trackID);
        m_timeStamp = x.m_timeStamp;
        m_threatScore = x.m_threatScore;
        m_threatLevel = x.m_threatLevel;
        m_trackCategoryId = x.m_trackCategoryId;
        m_trackCategoryName = std::move(x.m_trackCategoryName);
        m_trackAlias = std::move(x.m_trackAlias);
        m_isManual = x.m_isManual;
        m_modifiedBy = std::move(x.m_modifiedBy);
        m_modifiedTime = x.m_modifiedTime;
        m_reserved0 = x.m_reserved0;
        m_reserved1 = x.m_reserved1;
        m_reserved2 = x.m_reserved2;
        m_reserved3 = x.m_reserved3;
        m_reserved4 = x.m_reserved4;
        m_reserved5 = x.m_reserved5;
        m_reserved6 = std::move(x.m_reserved6);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object TrackDataClass that will be copied.
     */
    eProsima_user_DllExport TrackDataClass& operator =(
            const TrackDataClass& x)
    {

                    m_trackId = x.m_trackId;

                    m_mmsi = x.m_mmsi;

                    m_uniqueId = x.m_uniqueId;

                    m_longitude = x.m_longitude;

                    m_latitude = x.m_latitude;

                    m_course = x.m_course;

                    m_distance = x.m_distance;

                    m_speed = x.m_speed;

                    m_speed_N = x.m_speed_N;

                    m_speed__E = x.m_speed__E;

                    m_speed_V = x.m_speed_V;

                    m_height = x.m_height;

                    m_azimuth = x.m_azimuth;

                    m_range = x.m_range;

                    m_sizeMetres = x.m_sizeMetres;

                    m_sizeDegrees = x.m_sizeDegrees;

                    m_radarId = x.m_radarId;

                    m_dotID = x.m_dotID;

                    m_trackQuality = x.m_trackQuality;

                    m_fusion = x.m_fusion;

                    m_sensors = x.m_sensors;

                    m_trackID = x.m_trackID;

                    m_timeStamp = x.m_timeStamp;

                    m_threatScore = x.m_threatScore;

                    m_threatLevel = x.m_threatLevel;

                    m_trackCategoryId = x.m_trackCategoryId;

                    m_trackCategoryName = x.m_trackCategoryName;

                    m_trackAlias = x.m_trackAlias;

                    m_isManual = x.m_isManual;

                    m_modifiedBy = x.m_modifiedBy;

                    m_modifiedTime = x.m_modifiedTime;

                    m_reserved0 = x.m_reserved0;

                    m_reserved1 = x.m_reserved1;

                    m_reserved2 = x.m_reserved2;

                    m_reserved3 = x.m_reserved3;

                    m_reserved4 = x.m_reserved4;

                    m_reserved5 = x.m_reserved5;

                    m_reserved6 = x.m_reserved6;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object TrackDataClass that will be copied.
     */
    eProsima_user_DllExport TrackDataClass& operator =(
            TrackDataClass&& x) noexcept
    {

        m_trackId = x.m_trackId;
        m_mmsi = x.m_mmsi;
        m_uniqueId = x.m_uniqueId;
        m_longitude = x.m_longitude;
        m_latitude = x.m_latitude;
        m_course = x.m_course;
        m_distance = x.m_distance;
        m_speed = x.m_speed;
        m_speed_N = x.m_speed_N;
        m_speed__E = x.m_speed__E;
        m_speed_V = x.m_speed_V;
        m_height = x.m_height;
        m_azimuth = x.m_azimuth;
        m_range = x.m_range;
        m_sizeMetres = x.m_sizeMetres;
        m_sizeDegrees = x.m_sizeDegrees;
        m_radarId = std::move(x.m_radarId);
        m_dotID = x.m_dotID;
        m_trackQuality = x.m_trackQuality;
        m_fusion = x.m_fusion;
        m_sensors = x.m_sensors;
        m_trackID = std::move(x.m_trackID);
        m_timeStamp = x.m_timeStamp;
        m_threatScore = x.m_threatScore;
        m_threatLevel = x.m_threatLevel;
        m_trackCategoryId = x.m_trackCategoryId;
        m_trackCategoryName = std::move(x.m_trackCategoryName);
        m_trackAlias = std::move(x.m_trackAlias);
        m_isManual = x.m_isManual;
        m_modifiedBy = std::move(x.m_modifiedBy);
        m_modifiedTime = x.m_modifiedTime;
        m_reserved0 = x.m_reserved0;
        m_reserved1 = x.m_reserved1;
        m_reserved2 = x.m_reserved2;
        m_reserved3 = x.m_reserved3;
        m_reserved4 = x.m_reserved4;
        m_reserved5 = x.m_reserved5;
        m_reserved6 = std::move(x.m_reserved6);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x TrackDataClass object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TrackDataClass& x) const
    {
        return (m_trackId == x.m_trackId &&
           m_mmsi == x.m_mmsi &&
           m_uniqueId == x.m_uniqueId &&
           m_longitude == x.m_longitude &&
           m_latitude == x.m_latitude &&
           m_course == x.m_course &&
           m_distance == x.m_distance &&
           m_speed == x.m_speed &&
           m_speed_N == x.m_speed_N &&
           m_speed__E == x.m_speed__E &&
           m_speed_V == x.m_speed_V &&
           m_height == x.m_height &&
           m_azimuth == x.m_azimuth &&
           m_range == x.m_range &&
           m_sizeMetres == x.m_sizeMetres &&
           m_sizeDegrees == x.m_sizeDegrees &&
           m_radarId == x.m_radarId &&
           m_dotID == x.m_dotID &&
           m_trackQuality == x.m_trackQuality &&
           m_fusion == x.m_fusion &&
           m_sensors == x.m_sensors &&
           m_trackID == x.m_trackID &&
           m_timeStamp == x.m_timeStamp &&
           m_threatScore == x.m_threatScore &&
           m_threatLevel == x.m_threatLevel &&
           m_trackCategoryId == x.m_trackCategoryId &&
           m_trackCategoryName == x.m_trackCategoryName &&
           m_trackAlias == x.m_trackAlias &&
           m_isManual == x.m_isManual &&
           m_modifiedBy == x.m_modifiedBy &&
           m_modifiedTime == x.m_modifiedTime &&
           m_reserved0 == x.m_reserved0 &&
           m_reserved1 == x.m_reserved1 &&
           m_reserved2 == x.m_reserved2 &&
           m_reserved3 == x.m_reserved3 &&
           m_reserved4 == x.m_reserved4 &&
           m_reserved5 == x.m_reserved5 &&
           m_reserved6 == x.m_reserved6);
    }

    /*!
     * @brief Comparison operator.
     * @param x TrackDataClass object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TrackDataClass& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member trackId
     * @param _trackId New value for member trackId
     */
    eProsima_user_DllExport void trackId(
            uint32_t _trackId)
    {
        m_trackId = _trackId;
    }

    /*!
     * @brief This function returns the value of member trackId
     * @return Value of member trackId
     */
    eProsima_user_DllExport uint32_t trackId() const
    {
        return m_trackId;
    }

    /*!
     * @brief This function returns a reference to member trackId
     * @return Reference to member trackId
     */
    eProsima_user_DllExport uint32_t& trackId()
    {
        return m_trackId;
    }


    /*!
     * @brief This function sets a value in member mmsi
     * @param _mmsi New value for member mmsi
     */
    eProsima_user_DllExport void mmsi(
            uint32_t _mmsi)
    {
        m_mmsi = _mmsi;
    }

    /*!
     * @brief This function returns the value of member mmsi
     * @return Value of member mmsi
     */
    eProsima_user_DllExport uint32_t mmsi() const
    {
        return m_mmsi;
    }

    /*!
     * @brief This function returns a reference to member mmsi
     * @return Reference to member mmsi
     */
    eProsima_user_DllExport uint32_t& mmsi()
    {
        return m_mmsi;
    }


    /*!
     * @brief This function sets a value in member uniqueId
     * @param _uniqueId New value for member uniqueId
     */
    eProsima_user_DllExport void uniqueId(
            uint32_t _uniqueId)
    {
        m_uniqueId = _uniqueId;
    }

    /*!
     * @brief This function returns the value of member uniqueId
     * @return Value of member uniqueId
     */
    eProsima_user_DllExport uint32_t uniqueId() const
    {
        return m_uniqueId;
    }

    /*!
     * @brief This function returns a reference to member uniqueId
     * @return Reference to member uniqueId
     */
    eProsima_user_DllExport uint32_t& uniqueId()
    {
        return m_uniqueId;
    }


    /*!
     * @brief This function sets a value in member longitude
     * @param _longitude New value for member longitude
     */
    eProsima_user_DllExport void longitude(
            double _longitude)
    {
        m_longitude = _longitude;
    }

    /*!
     * @brief This function returns the value of member longitude
     * @return Value of member longitude
     */
    eProsima_user_DllExport double longitude() const
    {
        return m_longitude;
    }

    /*!
     * @brief This function returns a reference to member longitude
     * @return Reference to member longitude
     */
    eProsima_user_DllExport double& longitude()
    {
        return m_longitude;
    }


    /*!
     * @brief This function sets a value in member latitude
     * @param _latitude New value for member latitude
     */
    eProsima_user_DllExport void latitude(
            double _latitude)
    {
        m_latitude = _latitude;
    }

    /*!
     * @brief This function returns the value of member latitude
     * @return Value of member latitude
     */
    eProsima_user_DllExport double latitude() const
    {
        return m_latitude;
    }

    /*!
     * @brief This function returns a reference to member latitude
     * @return Reference to member latitude
     */
    eProsima_user_DllExport double& latitude()
    {
        return m_latitude;
    }


    /*!
     * @brief This function sets a value in member course
     * @param _course New value for member course
     */
    eProsima_user_DllExport void course(
            double _course)
    {
        m_course = _course;
    }

    /*!
     * @brief This function returns the value of member course
     * @return Value of member course
     */
    eProsima_user_DllExport double course() const
    {
        return m_course;
    }

    /*!
     * @brief This function returns a reference to member course
     * @return Reference to member course
     */
    eProsima_user_DllExport double& course()
    {
        return m_course;
    }


    /*!
     * @brief This function sets a value in member distance
     * @param _distance New value for member distance
     */
    eProsima_user_DllExport void distance(
            double _distance)
    {
        m_distance = _distance;
    }

    /*!
     * @brief This function returns the value of member distance
     * @return Value of member distance
     */
    eProsima_user_DllExport double distance() const
    {
        return m_distance;
    }

    /*!
     * @brief This function returns a reference to member distance
     * @return Reference to member distance
     */
    eProsima_user_DllExport double& distance()
    {
        return m_distance;
    }


    /*!
     * @brief This function sets a value in member speed
     * @param _speed New value for member speed
     */
    eProsima_user_DllExport void speed(
            double _speed)
    {
        m_speed = _speed;
    }

    /*!
     * @brief This function returns the value of member speed
     * @return Value of member speed
     */
    eProsima_user_DllExport double speed() const
    {
        return m_speed;
    }

    /*!
     * @brief This function returns a reference to member speed
     * @return Reference to member speed
     */
    eProsima_user_DllExport double& speed()
    {
        return m_speed;
    }


    /*!
     * @brief This function sets a value in member speed_N
     * @param _speed_N New value for member speed_N
     */
    eProsima_user_DllExport void speed_N(
            double _speed_N)
    {
        m_speed_N = _speed_N;
    }

    /*!
     * @brief This function returns the value of member speed_N
     * @return Value of member speed_N
     */
    eProsima_user_DllExport double speed_N() const
    {
        return m_speed_N;
    }

    /*!
     * @brief This function returns a reference to member speed_N
     * @return Reference to member speed_N
     */
    eProsima_user_DllExport double& speed_N()
    {
        return m_speed_N;
    }


    /*!
     * @brief This function sets a value in member speed__E
     * @param _speed__E New value for member speed__E
     */
    eProsima_user_DllExport void speed__E(
            double _speed__E)
    {
        m_speed__E = _speed__E;
    }

    /*!
     * @brief This function returns the value of member speed__E
     * @return Value of member speed__E
     */
    eProsima_user_DllExport double speed__E() const
    {
        return m_speed__E;
    }

    /*!
     * @brief This function returns a reference to member speed__E
     * @return Reference to member speed__E
     */
    eProsima_user_DllExport double& speed__E()
    {
        return m_speed__E;
    }


    /*!
     * @brief This function sets a value in member speed_V
     * @param _speed_V New value for member speed_V
     */
    eProsima_user_DllExport void speed_V(
            double _speed_V)
    {
        m_speed_V = _speed_V;
    }

    /*!
     * @brief This function returns the value of member speed_V
     * @return Value of member speed_V
     */
    eProsima_user_DllExport double speed_V() const
    {
        return m_speed_V;
    }

    /*!
     * @brief This function returns a reference to member speed_V
     * @return Reference to member speed_V
     */
    eProsima_user_DllExport double& speed_V()
    {
        return m_speed_V;
    }


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            double _height)
    {
        m_height = _height;
    }

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport double height() const
    {
        return m_height;
    }

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport double& height()
    {
        return m_height;
    }


    /*!
     * @brief This function sets a value in member azimuth
     * @param _azimuth New value for member azimuth
     */
    eProsima_user_DllExport void azimuth(
            double _azimuth)
    {
        m_azimuth = _azimuth;
    }

    /*!
     * @brief This function returns the value of member azimuth
     * @return Value of member azimuth
     */
    eProsima_user_DllExport double azimuth() const
    {
        return m_azimuth;
    }

    /*!
     * @brief This function returns a reference to member azimuth
     * @return Reference to member azimuth
     */
    eProsima_user_DllExport double& azimuth()
    {
        return m_azimuth;
    }


    /*!
     * @brief This function sets a value in member range
     * @param _range New value for member range
     */
    eProsima_user_DllExport void range(
            double _range)
    {
        m_range = _range;
    }

    /*!
     * @brief This function returns the value of member range
     * @return Value of member range
     */
    eProsima_user_DllExport double range() const
    {
        return m_range;
    }

    /*!
     * @brief This function returns a reference to member range
     * @return Reference to member range
     */
    eProsima_user_DllExport double& range()
    {
        return m_range;
    }


    /*!
     * @brief This function sets a value in member sizeMetres
     * @param _sizeMetres New value for member sizeMetres
     */
    eProsima_user_DllExport void sizeMetres(
            double _sizeMetres)
    {
        m_sizeMetres = _sizeMetres;
    }

    /*!
     * @brief This function returns the value of member sizeMetres
     * @return Value of member sizeMetres
     */
    eProsima_user_DllExport double sizeMetres() const
    {
        return m_sizeMetres;
    }

    /*!
     * @brief This function returns a reference to member sizeMetres
     * @return Reference to member sizeMetres
     */
    eProsima_user_DllExport double& sizeMetres()
    {
        return m_sizeMetres;
    }


    /*!
     * @brief This function sets a value in member sizeDegrees
     * @param _sizeDegrees New value for member sizeDegrees
     */
    eProsima_user_DllExport void sizeDegrees(
            double _sizeDegrees)
    {
        m_sizeDegrees = _sizeDegrees;
    }

    /*!
     * @brief This function returns the value of member sizeDegrees
     * @return Value of member sizeDegrees
     */
    eProsima_user_DllExport double sizeDegrees() const
    {
        return m_sizeDegrees;
    }

    /*!
     * @brief This function returns a reference to member sizeDegrees
     * @return Reference to member sizeDegrees
     */
    eProsima_user_DllExport double& sizeDegrees()
    {
        return m_sizeDegrees;
    }


    /*!
     * @brief This function copies the value in member radarId
     * @param _radarId New value to be copied in member radarId
     */
    eProsima_user_DllExport void radarId(
            const std::string& _radarId)
    {
        m_radarId = _radarId;
    }

    /*!
     * @brief This function moves the value in member radarId
     * @param _radarId New value to be moved in member radarId
     */
    eProsima_user_DllExport void radarId(
            std::string&& _radarId)
    {
        m_radarId = std::move(_radarId);
    }

    /*!
     * @brief This function returns a constant reference to member radarId
     * @return Constant reference to member radarId
     */
    eProsima_user_DllExport const std::string& radarId() const
    {
        return m_radarId;
    }

    /*!
     * @brief This function returns a reference to member radarId
     * @return Reference to member radarId
     */
    eProsima_user_DllExport std::string& radarId()
    {
        return m_radarId;
    }


    /*!
     * @brief This function sets a value in member dotID
     * @param _dotID New value for member dotID
     */
    eProsima_user_DllExport void dotID(
            uint32_t _dotID)
    {
        m_dotID = _dotID;
    }

    /*!
     * @brief This function returns the value of member dotID
     * @return Value of member dotID
     */
    eProsima_user_DllExport uint32_t dotID() const
    {
        return m_dotID;
    }

    /*!
     * @brief This function returns a reference to member dotID
     * @return Reference to member dotID
     */
    eProsima_user_DllExport uint32_t& dotID()
    {
        return m_dotID;
    }


    /*!
     * @brief This function sets a value in member trackQuality
     * @param _trackQuality New value for member trackQuality
     */
    eProsima_user_DllExport void trackQuality(
            uint8_t _trackQuality)
    {
        m_trackQuality = _trackQuality;
    }

    /*!
     * @brief This function returns the value of member trackQuality
     * @return Value of member trackQuality
     */
    eProsima_user_DllExport uint8_t trackQuality() const
    {
        return m_trackQuality;
    }

    /*!
     * @brief This function returns a reference to member trackQuality
     * @return Reference to member trackQuality
     */
    eProsima_user_DllExport uint8_t& trackQuality()
    {
        return m_trackQuality;
    }


    /*!
     * @brief This function sets a value in member fusion
     * @param _fusion New value for member fusion
     */
    eProsima_user_DllExport void fusion(
            uint8_t _fusion)
    {
        m_fusion = _fusion;
    }

    /*!
     * @brief This function returns the value of member fusion
     * @return Value of member fusion
     */
    eProsima_user_DllExport uint8_t fusion() const
    {
        return m_fusion;
    }

    /*!
     * @brief This function returns a reference to member fusion
     * @return Reference to member fusion
     */
    eProsima_user_DllExport uint8_t& fusion()
    {
        return m_fusion;
    }


    /*!
     * @brief This function sets a value in member sensors
     * @param _sensors New value for member sensors
     */
    eProsima_user_DllExport void sensors(
            uint32_t _sensors)
    {
        m_sensors = _sensors;
    }

    /*!
     * @brief This function returns the value of member sensors
     * @return Value of member sensors
     */
    eProsima_user_DllExport uint32_t sensors() const
    {
        return m_sensors;
    }

    /*!
     * @brief This function returns a reference to member sensors
     * @return Reference to member sensors
     */
    eProsima_user_DllExport uint32_t& sensors()
    {
        return m_sensors;
    }


    /*!
     * @brief This function copies the value in member trackID
     * @param _trackID New value to be copied in member trackID
     */
    eProsima_user_DllExport void trackID(
            const std::array<uint32_t, 8>& _trackID)
    {
        m_trackID = _trackID;
    }

    /*!
     * @brief This function moves the value in member trackID
     * @param _trackID New value to be moved in member trackID
     */
    eProsima_user_DllExport void trackID(
            std::array<uint32_t, 8>&& _trackID)
    {
        m_trackID = std::move(_trackID);
    }

    /*!
     * @brief This function returns a constant reference to member trackID
     * @return Constant reference to member trackID
     */
    eProsima_user_DllExport const std::array<uint32_t, 8>& trackID() const
    {
        return m_trackID;
    }

    /*!
     * @brief This function returns a reference to member trackID
     * @return Reference to member trackID
     */
    eProsima_user_DllExport std::array<uint32_t, 8>& trackID()
    {
        return m_trackID;
    }


    /*!
     * @brief This function sets a value in member timeStamp
     * @param _timeStamp New value for member timeStamp
     */
    eProsima_user_DllExport void timeStamp(
            uint32_t _timeStamp)
    {
        m_timeStamp = _timeStamp;
    }

    /*!
     * @brief This function returns the value of member timeStamp
     * @return Value of member timeStamp
     */
    eProsima_user_DllExport uint32_t timeStamp() const
    {
        return m_timeStamp;
    }

    /*!
     * @brief This function returns a reference to member timeStamp
     * @return Reference to member timeStamp
     */
    eProsima_user_DllExport uint32_t& timeStamp()
    {
        return m_timeStamp;
    }


    /*!
     * @brief This function sets a value in member threatScore
     * @param _threatScore New value for member threatScore
     */
    eProsima_user_DllExport void threatScore(
            double _threatScore)
    {
        m_threatScore = _threatScore;
    }

    /*!
     * @brief This function returns the value of member threatScore
     * @return Value of member threatScore
     */
    eProsima_user_DllExport double threatScore() const
    {
        return m_threatScore;
    }

    /*!
     * @brief This function returns a reference to member threatScore
     * @return Reference to member threatScore
     */
    eProsima_user_DllExport double& threatScore()
    {
        return m_threatScore;
    }


    /*!
     * @brief This function sets a value in member threatLevel
     * @param _threatLevel New value for member threatLevel
     */
    eProsima_user_DllExport void threatLevel(
            uint8_t _threatLevel)
    {
        m_threatLevel = _threatLevel;
    }

    /*!
     * @brief This function returns the value of member threatLevel
     * @return Value of member threatLevel
     */
    eProsima_user_DllExport uint8_t threatLevel() const
    {
        return m_threatLevel;
    }

    /*!
     * @brief This function returns a reference to member threatLevel
     * @return Reference to member threatLevel
     */
    eProsima_user_DllExport uint8_t& threatLevel()
    {
        return m_threatLevel;
    }


    /*!
     * @brief This function sets a value in member trackCategoryId
     * @param _trackCategoryId New value for member trackCategoryId
     */
    eProsima_user_DllExport void trackCategoryId(
            uint8_t _trackCategoryId)
    {
        m_trackCategoryId = _trackCategoryId;
    }

    /*!
     * @brief This function returns the value of member trackCategoryId
     * @return Value of member trackCategoryId
     */
    eProsima_user_DllExport uint8_t trackCategoryId() const
    {
        return m_trackCategoryId;
    }

    /*!
     * @brief This function returns a reference to member trackCategoryId
     * @return Reference to member trackCategoryId
     */
    eProsima_user_DllExport uint8_t& trackCategoryId()
    {
        return m_trackCategoryId;
    }


    /*!
     * @brief This function copies the value in member trackCategoryName
     * @param _trackCategoryName New value to be copied in member trackCategoryName
     */
    eProsima_user_DllExport void trackCategoryName(
            const std::string& _trackCategoryName)
    {
        m_trackCategoryName = _trackCategoryName;
    }

    /*!
     * @brief This function moves the value in member trackCategoryName
     * @param _trackCategoryName New value to be moved in member trackCategoryName
     */
    eProsima_user_DllExport void trackCategoryName(
            std::string&& _trackCategoryName)
    {
        m_trackCategoryName = std::move(_trackCategoryName);
    }

    /*!
     * @brief This function returns a constant reference to member trackCategoryName
     * @return Constant reference to member trackCategoryName
     */
    eProsima_user_DllExport const std::string& trackCategoryName() const
    {
        return m_trackCategoryName;
    }

    /*!
     * @brief This function returns a reference to member trackCategoryName
     * @return Reference to member trackCategoryName
     */
    eProsima_user_DllExport std::string& trackCategoryName()
    {
        return m_trackCategoryName;
    }


    /*!
     * @brief This function copies the value in member trackAlias
     * @param _trackAlias New value to be copied in member trackAlias
     */
    eProsima_user_DllExport void trackAlias(
            const std::string& _trackAlias)
    {
        m_trackAlias = _trackAlias;
    }

    /*!
     * @brief This function moves the value in member trackAlias
     * @param _trackAlias New value to be moved in member trackAlias
     */
    eProsima_user_DllExport void trackAlias(
            std::string&& _trackAlias)
    {
        m_trackAlias = std::move(_trackAlias);
    }

    /*!
     * @brief This function returns a constant reference to member trackAlias
     * @return Constant reference to member trackAlias
     */
    eProsima_user_DllExport const std::string& trackAlias() const
    {
        return m_trackAlias;
    }

    /*!
     * @brief This function returns a reference to member trackAlias
     * @return Reference to member trackAlias
     */
    eProsima_user_DllExport std::string& trackAlias()
    {
        return m_trackAlias;
    }


    /*!
     * @brief This function sets a value in member isManual
     * @param _isManual New value for member isManual
     */
    eProsima_user_DllExport void isManual(
            bool _isManual)
    {
        m_isManual = _isManual;
    }

    /*!
     * @brief This function returns the value of member isManual
     * @return Value of member isManual
     */
    eProsima_user_DllExport bool isManual() const
    {
        return m_isManual;
    }

    /*!
     * @brief This function returns a reference to member isManual
     * @return Reference to member isManual
     */
    eProsima_user_DllExport bool& isManual()
    {
        return m_isManual;
    }


    /*!
     * @brief This function copies the value in member modifiedBy
     * @param _modifiedBy New value to be copied in member modifiedBy
     */
    eProsima_user_DllExport void modifiedBy(
            const std::string& _modifiedBy)
    {
        m_modifiedBy = _modifiedBy;
    }

    /*!
     * @brief This function moves the value in member modifiedBy
     * @param _modifiedBy New value to be moved in member modifiedBy
     */
    eProsima_user_DllExport void modifiedBy(
            std::string&& _modifiedBy)
    {
        m_modifiedBy = std::move(_modifiedBy);
    }

    /*!
     * @brief This function returns a constant reference to member modifiedBy
     * @return Constant reference to member modifiedBy
     */
    eProsima_user_DllExport const std::string& modifiedBy() const
    {
        return m_modifiedBy;
    }

    /*!
     * @brief This function returns a reference to member modifiedBy
     * @return Reference to member modifiedBy
     */
    eProsima_user_DllExport std::string& modifiedBy()
    {
        return m_modifiedBy;
    }


    /*!
     * @brief This function sets a value in member modifiedTime
     * @param _modifiedTime New value for member modifiedTime
     */
    eProsima_user_DllExport void modifiedTime(
            uint32_t _modifiedTime)
    {
        m_modifiedTime = _modifiedTime;
    }

    /*!
     * @brief This function returns the value of member modifiedTime
     * @return Value of member modifiedTime
     */
    eProsima_user_DllExport uint32_t modifiedTime() const
    {
        return m_modifiedTime;
    }

    /*!
     * @brief This function returns a reference to member modifiedTime
     * @return Reference to member modifiedTime
     */
    eProsima_user_DllExport uint32_t& modifiedTime()
    {
        return m_modifiedTime;
    }


    /*!
     * @brief This function sets a value in member reserved0
     * @param _reserved0 New value for member reserved0
     */
    eProsima_user_DllExport void reserved0(
            uint8_t _reserved0)
    {
        m_reserved0 = _reserved0;
    }

    /*!
     * @brief This function returns the value of member reserved0
     * @return Value of member reserved0
     */
    eProsima_user_DllExport uint8_t reserved0() const
    {
        return m_reserved0;
    }

    /*!
     * @brief This function returns a reference to member reserved0
     * @return Reference to member reserved0
     */
    eProsima_user_DllExport uint8_t& reserved0()
    {
        return m_reserved0;
    }


    /*!
     * @brief This function sets a value in member reserved1
     * @param _reserved1 New value for member reserved1
     */
    eProsima_user_DllExport void reserved1(
            uint8_t _reserved1)
    {
        m_reserved1 = _reserved1;
    }

    /*!
     * @brief This function returns the value of member reserved1
     * @return Value of member reserved1
     */
    eProsima_user_DllExport uint8_t reserved1() const
    {
        return m_reserved1;
    }

    /*!
     * @brief This function returns a reference to member reserved1
     * @return Reference to member reserved1
     */
    eProsima_user_DllExport uint8_t& reserved1()
    {
        return m_reserved1;
    }


    /*!
     * @brief This function sets a value in member reserved2
     * @param _reserved2 New value for member reserved2
     */
    eProsima_user_DllExport void reserved2(
            double _reserved2)
    {
        m_reserved2 = _reserved2;
    }

    /*!
     * @brief This function returns the value of member reserved2
     * @return Value of member reserved2
     */
    eProsima_user_DllExport double reserved2() const
    {
        return m_reserved2;
    }

    /*!
     * @brief This function returns a reference to member reserved2
     * @return Reference to member reserved2
     */
    eProsima_user_DllExport double& reserved2()
    {
        return m_reserved2;
    }


    /*!
     * @brief This function sets a value in member reserved3
     * @param _reserved3 New value for member reserved3
     */
    eProsima_user_DllExport void reserved3(
            double _reserved3)
    {
        m_reserved3 = _reserved3;
    }

    /*!
     * @brief This function returns the value of member reserved3
     * @return Value of member reserved3
     */
    eProsima_user_DllExport double reserved3() const
    {
        return m_reserved3;
    }

    /*!
     * @brief This function returns a reference to member reserved3
     * @return Reference to member reserved3
     */
    eProsima_user_DllExport double& reserved3()
    {
        return m_reserved3;
    }


    /*!
     * @brief This function sets a value in member reserved4
     * @param _reserved4 New value for member reserved4
     */
    eProsima_user_DllExport void reserved4(
            uint32_t _reserved4)
    {
        m_reserved4 = _reserved4;
    }

    /*!
     * @brief This function returns the value of member reserved4
     * @return Value of member reserved4
     */
    eProsima_user_DllExport uint32_t reserved4() const
    {
        return m_reserved4;
    }

    /*!
     * @brief This function returns a reference to member reserved4
     * @return Reference to member reserved4
     */
    eProsima_user_DllExport uint32_t& reserved4()
    {
        return m_reserved4;
    }


    /*!
     * @brief This function sets a value in member reserved5
     * @param _reserved5 New value for member reserved5
     */
    eProsima_user_DllExport void reserved5(
            uint32_t _reserved5)
    {
        m_reserved5 = _reserved5;
    }

    /*!
     * @brief This function returns the value of member reserved5
     * @return Value of member reserved5
     */
    eProsima_user_DllExport uint32_t reserved5() const
    {
        return m_reserved5;
    }

    /*!
     * @brief This function returns a reference to member reserved5
     * @return Reference to member reserved5
     */
    eProsima_user_DllExport uint32_t& reserved5()
    {
        return m_reserved5;
    }


    /*!
     * @brief This function copies the value in member reserved6
     * @param _reserved6 New value to be copied in member reserved6
     */
    eProsima_user_DllExport void reserved6(
            const std::string& _reserved6)
    {
        m_reserved6 = _reserved6;
    }

    /*!
     * @brief This function moves the value in member reserved6
     * @param _reserved6 New value to be moved in member reserved6
     */
    eProsima_user_DllExport void reserved6(
            std::string&& _reserved6)
    {
        m_reserved6 = std::move(_reserved6);
    }

    /*!
     * @brief This function returns a constant reference to member reserved6
     * @return Constant reference to member reserved6
     */
    eProsima_user_DllExport const std::string& reserved6() const
    {
        return m_reserved6;
    }

    /*!
     * @brief This function returns a reference to member reserved6
     * @return Reference to member reserved6
     */
    eProsima_user_DllExport std::string& reserved6()
    {
        return m_reserved6;
    }



private:

    uint32_t m_trackId{0};
    uint32_t m_mmsi{0};
    uint32_t m_uniqueId{0};
    double m_longitude{0.0};
    double m_latitude{0.0};
    double m_course{0.0};
    double m_distance{0.0};
    double m_speed{0.0};
    double m_speed_N{0.0};
    double m_speed__E{0.0};
    double m_speed_V{0.0};
    double m_height{0.0};
    double m_azimuth{0.0};
    double m_range{0.0};
    double m_sizeMetres{0.0};
    double m_sizeDegrees{0.0};
    std::string m_radarId;
    uint32_t m_dotID{0};
    uint8_t m_trackQuality{0};
    uint8_t m_fusion{0};
    uint32_t m_sensors{0};
    std::array<uint32_t, 8> m_trackID{0};
    uint32_t m_timeStamp{0};
    double m_threatScore{0.0};
    uint8_t m_threatLevel{0};
    uint8_t m_trackCategoryId{0};
    std::string m_trackCategoryName;
    std::string m_trackAlias;
    bool m_isManual{false};
    std::string m_modifiedBy;
    uint32_t m_modifiedTime{0};
    uint8_t m_reserved0{0};
    uint8_t m_reserved1{0};
    double m_reserved2{0.0};
    double m_reserved3{0.0};
    uint32_t m_reserved4{0};
    uint32_t m_reserved5{0};
    std::string m_reserved6;

};

#endif // _FAST_DDS_GENERATED_TRACKCLASS_HPP_


