// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AlarmEventSubscriberApp.cxx
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "AlarmEventSubscriberApp.hpp"

#include <condition_variable>
#include <stdexcept>

#include <QSettings>
#include <fastdds/dds/core/status/SubscriptionMatchedStatus.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/qos/DataReaderQos.hpp>
#include <fastdds/dds/subscriber/qos/SubscriberQos.hpp>
#include <fastdds/dds/subscriber/SampleInfo.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>

#include "AlarmEventPubSubTypes.hpp"

using namespace eprosima::fastdds::dds;

namespace {
struct AlarmEventSubDdsConfig {
    bool useProfile = false;
    QString xmlFile = QStringLiteral("alarmevent_multi.xml");
    QString participantProfile = QStringLiteral("participant_alarmevent");
    QString topicName = QStringLiteral("AlarmEventTopic");
};

AlarmEventSubDdsConfig loadAlarmEventSubDdsConfig()
{
    AlarmEventSubDdsConfig c;
    QSettings s(QStringLiteral("Config.ini"), QSettings::IniFormat);
    c.useProfile = s.value(QStringLiteral("DDS/AlarmEventSubUseProfile"), 0).toInt() != 0;
    c.xmlFile = s.value(QStringLiteral("DDS/AlarmEventSubXml"), c.xmlFile).toString();
    c.participantProfile = s.value(QStringLiteral("DDS/AlarmEventSubParticipantProfile"), c.participantProfile).toString();
    c.topicName = s.value(QStringLiteral("DDS/AlarmEventSubTopic"), c.topicName).toString();
    return c;
}
}

AlarmEventSubscriberApp::AlarmEventSubscriberApp(
    const int& domain_id)
    : factory_(nullptr)
    , participant_(nullptr)
    , subscriber_(nullptr)
    , topic_(nullptr)
    , reader_(nullptr)
    , type_(new casia::event::alarm::AlarmEventPubSubType())
    , samples_received_(0)
    , stop_(false)
{
    const AlarmEventSubDdsConfig ddsCfg = loadAlarmEventSubDdsConfig();
    // Create the participant
    DomainParticipantQos pqos = PARTICIPANT_QOS_DEFAULT;
    pqos.name("casia::event::alarm::AlarmEvent_sub_participant");
    factory_ = DomainParticipantFactory::get_shared_instance();
    if (ddsCfg.useProfile) {
        factory_->load_XML_profiles_file(ddsCfg.xmlFile.toStdString());
        participant_ = factory_->create_participant_with_profile(domain_id, ddsCfg.participantProfile.toStdString());
    } else {
        participant_ = factory_->create_participant(domain_id, pqos, nullptr, StatusMask::none());
    }
    if (participant_ == nullptr)
    {
        throw std::runtime_error("casia::event::alarm::AlarmEvent Participant initialization failed");
    }

    // Register the type
    type_.register_type(participant_);

    // Create the subscriber
    SubscriberQos sub_qos = SUBSCRIBER_QOS_DEFAULT;
    participant_->get_default_subscriber_qos(sub_qos);
    subscriber_ = participant_->create_subscriber(sub_qos, nullptr, StatusMask::none());
    if (subscriber_ == nullptr)
    {
        throw std::runtime_error("casia::event::alarm::AlarmEvent Subscriber initialization failed");
    }

    // Create the topic
    TopicQos topic_qos = TOPIC_QOS_DEFAULT;
    participant_->get_default_topic_qos(topic_qos);
    topic_ = participant_->create_topic(ddsCfg.topicName.toStdString(), type_.get_type_name(), topic_qos);
    if (topic_ == nullptr)
    {
        throw std::runtime_error("casia::event::alarm::AlarmEvent Topic initialization failed");
    }

    // Create the reader
    DataReaderQos reader_qos = DATAREADER_QOS_DEFAULT;
    subscriber_->get_default_datareader_qos(reader_qos);
    reader_qos.reliability().kind = ReliabilityQosPolicyKind::RELIABLE_RELIABILITY_QOS;
    reader_qos.durability().kind = DurabilityQosPolicyKind::TRANSIENT_LOCAL_DURABILITY_QOS;
    reader_qos.history().kind = HistoryQosPolicyKind::KEEP_ALL_HISTORY_QOS;
    reader_ = subscriber_->create_datareader(topic_, reader_qos, this, StatusMask::all());
    if (reader_ == nullptr)
    {
        throw std::runtime_error("casia::event::alarm::AlarmEvent DataReader initialization failed");
    }
}

AlarmEventSubscriberApp::~AlarmEventSubscriberApp()
{
    if (nullptr != participant_)
    {
        // Delete DDS entities contained within the DomainParticipant
        participant_->delete_contained_entities();

        // Delete DomainParticipant
        if (factory_)
            factory_->delete_participant(participant_);
        else
            DomainParticipantFactory::get_instance()->delete_participant(participant_);
    }
}

void AlarmEventSubscriberApp::on_subscription_matched(
    DataReader* /*reader*/,
    const SubscriptionMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        std::cout << "casia::event::alarm::AlarmEvent Subscriber matched." << std::endl;
    }
    else if (info.current_count_change == -1)
    {
        std::cout << "casia::event::alarm::AlarmEvent Subscriber unmatched." << std::endl;
    }
    else
    {
        std::cout << info.current_count_change
            << " is not a valid value for SubscriptionMatchedStatus current count change" << std::endl;
    }
}

void AlarmEventSubscriberApp::on_data_available(
    DataReader* reader)
{
    casia::event::alarm::AlarmEvent sample_;
    SampleInfo info;
    while ((!is_stopped()) && (RETCODE_OK == reader->take_next_sample(&sample_, &info)))
    {
        if ((info.instance_state == ALIVE_INSTANCE_STATE) && info.valid_data)
        {
            std::cout << "Sample '" << std::to_string(++samples_received_) << "' RECEIVED" << std::endl;
        }
    }
}

void AlarmEventSubscriberApp::run()
{
    std::unique_lock<std::mutex> lck(terminate_cv_mtx_);
    terminate_cv_.wait(lck, [this]
        {
            return is_stopped();
        });
}

bool AlarmEventSubscriberApp::is_stopped()
{
    return stop_.load();
}

void AlarmEventSubscriberApp::stop()
{
    stop_.store(true);
    terminate_cv_.notify_all();
}