// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AlarmEvent.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__CASIA_EVENT_ALARM_ALARMEVENT_HPP
#define FAST_DDS_GENERATED__CASIA_EVENT_ALARM_ALARMEVENT_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include "BaseEvent.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ALARMEVENT_SOURCE)
#define ALARMEVENT_DllAPI __declspec( dllexport )
#else
#define ALARMEVENT_DllAPI __declspec( dllimport )
#endif // ALARMEVENT_SOURCE
#else
#define ALARMEVENT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ALARMEVENT_DllAPI
#endif // _WIN32

namespace casia {

namespace event {

namespace alarm {

/*!
 * @brief This class represents the enumeration AlarmType defined by the user in the IDL file.
 * @ingroup AlarmEvent
 */
enum class AlarmType : int32_t
{
    TRACK_AREA,
    TARGET_BEHAVIOR,
    TARGET_ATTR,
    DEVICE,
    CUSTOM_TYPE
};
/*!
 * @brief This class represents the enumeration TrackType defined by the user in the IDL file.
 * @ingroup AlarmEvent
 */
enum class TrackType : int32_t
{
    FUSE,
    BIRD
};
/*!
 * @brief This class represents the enumeration AlarmStatus defined by the user in the IDL file.
 * @ingroup AlarmEvent
 */
enum class AlarmStatus : int32_t
{
    ACTIVE,
    CANCELED,
    DELETED,
    FOCUS,
    AUTO_RESOLVED
};
/*!
 * @brief This class represents the enumeration AlarmTaskStatus defined by the user in the IDL file.
 * @ingroup AlarmEvent
 */
enum class AlarmTaskStatus : int32_t
{
    UNASSIGNED,
    ASSIGNED,
    VERIFY_FAILED,
    VERIFY_SUCCESS
};
/*!
 * @brief This class represents the structure BoundingBox defined by the user in the IDL file.
 * @ingroup AlarmEvent
 */
class BoundingBox
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport BoundingBox()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~BoundingBox()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object BoundingBox that will be copied.
     */
    eProsima_user_DllExport BoundingBox(
            const BoundingBox& x)
    {
                    m_cameraId = x.m_cameraId;

                    m_syncHeader = x.m_syncHeader;

                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_width = x.m_width;

                    m_height = x.m_height;

                    m_boxId = x.m_boxId;

                    m_trackId = x.m_trackId;

                    m_classId = x.m_classId;

                    m_behaviorId = x.m_behaviorId;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object BoundingBox that will be copied.
     */
    eProsima_user_DllExport BoundingBox(
            BoundingBox&& x) noexcept
    {
        m_cameraId = std::move(x.m_cameraId);
        m_syncHeader = std::move(x.m_syncHeader);
        m_x = x.m_x;
        m_y = x.m_y;
        m_width = x.m_width;
        m_height = x.m_height;
        m_boxId = x.m_boxId;
        m_trackId = x.m_trackId;
        m_classId = x.m_classId;
        m_behaviorId = x.m_behaviorId;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object BoundingBox that will be copied.
     */
    eProsima_user_DllExport BoundingBox& operator =(
            const BoundingBox& x)
    {

                    m_cameraId = x.m_cameraId;

                    m_syncHeader = x.m_syncHeader;

                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_width = x.m_width;

                    m_height = x.m_height;

                    m_boxId = x.m_boxId;

                    m_trackId = x.m_trackId;

                    m_classId = x.m_classId;

                    m_behaviorId = x.m_behaviorId;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object BoundingBox that will be copied.
     */
    eProsima_user_DllExport BoundingBox& operator =(
            BoundingBox&& x) noexcept
    {

        m_cameraId = std::move(x.m_cameraId);
        m_syncHeader = std::move(x.m_syncHeader);
        m_x = x.m_x;
        m_y = x.m_y;
        m_width = x.m_width;
        m_height = x.m_height;
        m_boxId = x.m_boxId;
        m_trackId = x.m_trackId;
        m_classId = x.m_classId;
        m_behaviorId = x.m_behaviorId;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x BoundingBox object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const BoundingBox& x) const
    {
        return (m_cameraId == x.m_cameraId &&
           m_syncHeader == x.m_syncHeader &&
           m_x == x.m_x &&
           m_y == x.m_y &&
           m_width == x.m_width &&
           m_height == x.m_height &&
           m_boxId == x.m_boxId &&
           m_trackId == x.m_trackId &&
           m_classId == x.m_classId &&
           m_behaviorId == x.m_behaviorId);
    }

    /*!
     * @brief Comparison operator.
     * @param x BoundingBox object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const BoundingBox& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member cameraId
     * @param _cameraId New value to be copied in member cameraId
     */
    eProsima_user_DllExport void cameraId(
            const std::string& _cameraId)
    {
        m_cameraId = _cameraId;
    }

    /*!
     * @brief This function moves the value in member cameraId
     * @param _cameraId New value to be moved in member cameraId
     */
    eProsima_user_DllExport void cameraId(
            std::string&& _cameraId)
    {
        m_cameraId = std::move(_cameraId);
    }

    /*!
     * @brief This function returns a constant reference to member cameraId
     * @return Constant reference to member cameraId
     */
    eProsima_user_DllExport const std::string& cameraId() const
    {
        return m_cameraId;
    }

    /*!
     * @brief This function returns a reference to member cameraId
     * @return Reference to member cameraId
     */
    eProsima_user_DllExport std::string& cameraId()
    {
        return m_cameraId;
    }


    /*!
     * @brief This function copies the value in member syncHeader
     * @param _syncHeader New value to be copied in member syncHeader
     */
    eProsima_user_DllExport void syncHeader(
            const std::string& _syncHeader)
    {
        m_syncHeader = _syncHeader;
    }

    /*!
     * @brief This function moves the value in member syncHeader
     * @param _syncHeader New value to be moved in member syncHeader
     */
    eProsima_user_DllExport void syncHeader(
            std::string&& _syncHeader)
    {
        m_syncHeader = std::move(_syncHeader);
    }

    /*!
     * @brief This function returns a constant reference to member syncHeader
     * @return Constant reference to member syncHeader
     */
    eProsima_user_DllExport const std::string& syncHeader() const
    {
        return m_syncHeader;
    }

    /*!
     * @brief This function returns a reference to member syncHeader
     * @return Reference to member syncHeader
     */
    eProsima_user_DllExport std::string& syncHeader()
    {
        return m_syncHeader;
    }


    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    eProsima_user_DllExport void x(
            int16_t _x)
    {
        m_x = _x;
    }

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    eProsima_user_DllExport int16_t x() const
    {
        return m_x;
    }

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport int16_t& x()
    {
        return m_x;
    }


    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    eProsima_user_DllExport void y(
            int16_t _y)
    {
        m_y = _y;
    }

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    eProsima_user_DllExport int16_t y() const
    {
        return m_y;
    }

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    eProsima_user_DllExport int16_t& y()
    {
        return m_y;
    }


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            int16_t _width)
    {
        m_width = _width;
    }

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport int16_t width() const
    {
        return m_width;
    }

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport int16_t& width()
    {
        return m_width;
    }


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            int16_t _height)
    {
        m_height = _height;
    }

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport int16_t height() const
    {
        return m_height;
    }

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport int16_t& height()
    {
        return m_height;
    }


    /*!
     * @brief This function sets a value in member boxId
     * @param _boxId New value for member boxId
     */
    eProsima_user_DllExport void boxId(
            int32_t _boxId)
    {
        m_boxId = _boxId;
    }

    /*!
     * @brief This function returns the value of member boxId
     * @return Value of member boxId
     */
    eProsima_user_DllExport int32_t boxId() const
    {
        return m_boxId;
    }

    /*!
     * @brief This function returns a reference to member boxId
     * @return Reference to member boxId
     */
    eProsima_user_DllExport int32_t& boxId()
    {
        return m_boxId;
    }


    /*!
     * @brief This function sets a value in member trackId
     * @param _trackId New value for member trackId
     */
    eProsima_user_DllExport void trackId(
            int32_t _trackId)
    {
        m_trackId = _trackId;
    }

    /*!
     * @brief This function returns the value of member trackId
     * @return Value of member trackId
     */
    eProsima_user_DllExport int32_t trackId() const
    {
        return m_trackId;
    }

    /*!
     * @brief This function returns a reference to member trackId
     * @return Reference to member trackId
     */
    eProsima_user_DllExport int32_t& trackId()
    {
        return m_trackId;
    }


    /*!
     * @brief This function sets a value in member classId
     * @param _classId New value for member classId
     */
    eProsima_user_DllExport void classId(
            int32_t _classId)
    {
        m_classId = _classId;
    }

    /*!
     * @brief This function returns the value of member classId
     * @return Value of member classId
     */
    eProsima_user_DllExport int32_t classId() const
    {
        return m_classId;
    }

    /*!
     * @brief This function returns a reference to member classId
     * @return Reference to member classId
     */
    eProsima_user_DllExport int32_t& classId()
    {
        return m_classId;
    }


    /*!
     * @brief This function sets a value in member behaviorId
     * @param _behaviorId New value for member behaviorId
     */
    eProsima_user_DllExport void behaviorId(
            int32_t _behaviorId)
    {
        m_behaviorId = _behaviorId;
    }

    /*!
     * @brief This function returns the value of member behaviorId
     * @return Value of member behaviorId
     */
    eProsima_user_DllExport int32_t behaviorId() const
    {
        return m_behaviorId;
    }

    /*!
     * @brief This function returns a reference to member behaviorId
     * @return Reference to member behaviorId
     */
    eProsima_user_DllExport int32_t& behaviorId()
    {
        return m_behaviorId;
    }



private:

    std::string m_cameraId;
    std::string m_syncHeader;
    int16_t m_x{0};
    int16_t m_y{0};
    int16_t m_width{0};
    int16_t m_height{0};
    int32_t m_boxId{0};
    int32_t m_trackId{0};
    int32_t m_classId{0};
    int32_t m_behaviorId{0};

};
/*!
 * @brief This class represents the structure TrackData defined by the user in the IDL file.
 * @ingroup AlarmEvent
 */
class TrackData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TrackData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TrackData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object TrackData that will be copied.
     */
    eProsima_user_DllExport TrackData(
            const TrackData& x)
    {
                    m_trackId = x.m_trackId;

                    m_mmsi = x.m_mmsi;

                    m_longitude = x.m_longitude;

                    m_latitude = x.m_latitude;

                    m_course = x.m_course;

                    m_speed = x.m_speed;

                    m_height = x.m_height;

                    m_timeStamp = x.m_timeStamp;

                    m_trackType = x.m_trackType;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object TrackData that will be copied.
     */
    eProsima_user_DllExport TrackData(
            TrackData&& x) noexcept
    {
        m_trackId = x.m_trackId;
        m_mmsi = x.m_mmsi;
        m_longitude = x.m_longitude;
        m_latitude = x.m_latitude;
        m_course = x.m_course;
        m_speed = x.m_speed;
        m_height = x.m_height;
        m_timeStamp = x.m_timeStamp;
        m_trackType = x.m_trackType;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object TrackData that will be copied.
     */
    eProsima_user_DllExport TrackData& operator =(
            const TrackData& x)
    {

                    m_trackId = x.m_trackId;

                    m_mmsi = x.m_mmsi;

                    m_longitude = x.m_longitude;

                    m_latitude = x.m_latitude;

                    m_course = x.m_course;

                    m_speed = x.m_speed;

                    m_height = x.m_height;

                    m_timeStamp = x.m_timeStamp;

                    m_trackType = x.m_trackType;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object TrackData that will be copied.
     */
    eProsima_user_DllExport TrackData& operator =(
            TrackData&& x) noexcept
    {

        m_trackId = x.m_trackId;
        m_mmsi = x.m_mmsi;
        m_longitude = x.m_longitude;
        m_latitude = x.m_latitude;
        m_course = x.m_course;
        m_speed = x.m_speed;
        m_height = x.m_height;
        m_timeStamp = x.m_timeStamp;
        m_trackType = x.m_trackType;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x TrackData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TrackData& x) const
    {
        return (m_trackId == x.m_trackId &&
           m_mmsi == x.m_mmsi &&
           m_longitude == x.m_longitude &&
           m_latitude == x.m_latitude &&
           m_course == x.m_course &&
           m_speed == x.m_speed &&
           m_height == x.m_height &&
           m_timeStamp == x.m_timeStamp &&
           m_trackType == x.m_trackType);
    }

    /*!
     * @brief Comparison operator.
     * @param x TrackData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TrackData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member trackId
     * @param _trackId New value for member trackId
     */
    eProsima_user_DllExport void trackId(
            uint32_t _trackId)
    {
        m_trackId = _trackId;
    }

    /*!
     * @brief This function returns the value of member trackId
     * @return Value of member trackId
     */
    eProsima_user_DllExport uint32_t trackId() const
    {
        return m_trackId;
    }

    /*!
     * @brief This function returns a reference to member trackId
     * @return Reference to member trackId
     */
    eProsima_user_DllExport uint32_t& trackId()
    {
        return m_trackId;
    }


    /*!
     * @brief This function sets a value in member mmsi
     * @param _mmsi New value for member mmsi
     */
    eProsima_user_DllExport void mmsi(
            uint32_t _mmsi)
    {
        m_mmsi = _mmsi;
    }

    /*!
     * @brief This function returns the value of member mmsi
     * @return Value of member mmsi
     */
    eProsima_user_DllExport uint32_t mmsi() const
    {
        return m_mmsi;
    }

    /*!
     * @brief This function returns a reference to member mmsi
     * @return Reference to member mmsi
     */
    eProsima_user_DllExport uint32_t& mmsi()
    {
        return m_mmsi;
    }


    /*!
     * @brief This function sets a value in member longitude
     * @param _longitude New value for member longitude
     */
    eProsima_user_DllExport void longitude(
            double _longitude)
    {
        m_longitude = _longitude;
    }

    /*!
     * @brief This function returns the value of member longitude
     * @return Value of member longitude
     */
    eProsima_user_DllExport double longitude() const
    {
        return m_longitude;
    }

    /*!
     * @brief This function returns a reference to member longitude
     * @return Reference to member longitude
     */
    eProsima_user_DllExport double& longitude()
    {
        return m_longitude;
    }


    /*!
     * @brief This function sets a value in member latitude
     * @param _latitude New value for member latitude
     */
    eProsima_user_DllExport void latitude(
            double _latitude)
    {
        m_latitude = _latitude;
    }

    /*!
     * @brief This function returns the value of member latitude
     * @return Value of member latitude
     */
    eProsima_user_DllExport double latitude() const
    {
        return m_latitude;
    }

    /*!
     * @brief This function returns a reference to member latitude
     * @return Reference to member latitude
     */
    eProsima_user_DllExport double& latitude()
    {
        return m_latitude;
    }


    /*!
     * @brief This function sets a value in member course
     * @param _course New value for member course
     */
    eProsima_user_DllExport void course(
            double _course)
    {
        m_course = _course;
    }

    /*!
     * @brief This function returns the value of member course
     * @return Value of member course
     */
    eProsima_user_DllExport double course() const
    {
        return m_course;
    }

    /*!
     * @brief This function returns a reference to member course
     * @return Reference to member course
     */
    eProsima_user_DllExport double& course()
    {
        return m_course;
    }


    /*!
     * @brief This function sets a value in member speed
     * @param _speed New value for member speed
     */
    eProsima_user_DllExport void speed(
            double _speed)
    {
        m_speed = _speed;
    }

    /*!
     * @brief This function returns the value of member speed
     * @return Value of member speed
     */
    eProsima_user_DllExport double speed() const
    {
        return m_speed;
    }

    /*!
     * @brief This function returns a reference to member speed
     * @return Reference to member speed
     */
    eProsima_user_DllExport double& speed()
    {
        return m_speed;
    }


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            double _height)
    {
        m_height = _height;
    }

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport double height() const
    {
        return m_height;
    }

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport double& height()
    {
        return m_height;
    }


    /*!
     * @brief This function sets a value in member timeStamp
     * @param _timeStamp New value for member timeStamp
     */
    eProsima_user_DllExport void timeStamp(
            uint32_t _timeStamp)
    {
        m_timeStamp = _timeStamp;
    }

    /*!
     * @brief This function returns the value of member timeStamp
     * @return Value of member timeStamp
     */
    eProsima_user_DllExport uint32_t timeStamp() const
    {
        return m_timeStamp;
    }

    /*!
     * @brief This function returns a reference to member timeStamp
     * @return Reference to member timeStamp
     */
    eProsima_user_DllExport uint32_t& timeStamp()
    {
        return m_timeStamp;
    }


    /*!
     * @brief This function sets a value in member trackType
     * @param _trackType New value for member trackType
     */
    eProsima_user_DllExport void trackType(
            TrackType _trackType)
    {
        m_trackType = _trackType;
    }

    /*!
     * @brief This function returns the value of member trackType
     * @return Value of member trackType
     */
    eProsima_user_DllExport TrackType trackType() const
    {
        return m_trackType;
    }

    /*!
     * @brief This function returns a reference to member trackType
     * @return Reference to member trackType
     */
    eProsima_user_DllExport TrackType& trackType()
    {
        return m_trackType;
    }



private:

    uint32_t m_trackId{0};
    uint32_t m_mmsi{0};
    double m_longitude{0.0};
    double m_latitude{0.0};
    double m_course{0.0};
    double m_speed{0.0};
    double m_height{0.0};
    uint32_t m_timeStamp{0};
    TrackType m_trackType{TrackType::FUSE};

};
/*!
 * @brief This class represents the structure GeoPosition defined by the user in the IDL file.
 * @ingroup AlarmEvent
 */
class GeoPosition
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GeoPosition()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GeoPosition()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GeoPosition that will be copied.
     */
    eProsima_user_DllExport GeoPosition(
            const GeoPosition& x)
    {
                    m_longitude = x.m_longitude;

                    m_latitude = x.m_latitude;

                    m_altitude = x.m_altitude;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GeoPosition that will be copied.
     */
    eProsima_user_DllExport GeoPosition(
            GeoPosition&& x) noexcept
    {
        m_longitude = x.m_longitude;
        m_latitude = x.m_latitude;
        m_altitude = x.m_altitude;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GeoPosition that will be copied.
     */
    eProsima_user_DllExport GeoPosition& operator =(
            const GeoPosition& x)
    {

                    m_longitude = x.m_longitude;

                    m_latitude = x.m_latitude;

                    m_altitude = x.m_altitude;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GeoPosition that will be copied.
     */
    eProsima_user_DllExport GeoPosition& operator =(
            GeoPosition&& x) noexcept
    {

        m_longitude = x.m_longitude;
        m_latitude = x.m_latitude;
        m_altitude = x.m_altitude;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GeoPosition object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GeoPosition& x) const
    {
        return (m_longitude == x.m_longitude &&
           m_latitude == x.m_latitude &&
           m_altitude == x.m_altitude);
    }

    /*!
     * @brief Comparison operator.
     * @param x GeoPosition object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GeoPosition& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member longitude
     * @param _longitude New value for member longitude
     */
    eProsima_user_DllExport void longitude(
            double _longitude)
    {
        m_longitude = _longitude;
    }

    /*!
     * @brief This function returns the value of member longitude
     * @return Value of member longitude
     */
    eProsima_user_DllExport double longitude() const
    {
        return m_longitude;
    }

    /*!
     * @brief This function returns a reference to member longitude
     * @return Reference to member longitude
     */
    eProsima_user_DllExport double& longitude()
    {
        return m_longitude;
    }


    /*!
     * @brief This function sets a value in member latitude
     * @param _latitude New value for member latitude
     */
    eProsima_user_DllExport void latitude(
            double _latitude)
    {
        m_latitude = _latitude;
    }

    /*!
     * @brief This function returns the value of member latitude
     * @return Value of member latitude
     */
    eProsima_user_DllExport double latitude() const
    {
        return m_latitude;
    }

    /*!
     * @brief This function returns a reference to member latitude
     * @return Reference to member latitude
     */
    eProsima_user_DllExport double& latitude()
    {
        return m_latitude;
    }


    /*!
     * @brief This function sets a value in member altitude
     * @param _altitude New value for member altitude
     */
    eProsima_user_DllExport void altitude(
            double _altitude)
    {
        m_altitude = _altitude;
    }

    /*!
     * @brief This function returns the value of member altitude
     * @return Value of member altitude
     */
    eProsima_user_DllExport double altitude() const
    {
        return m_altitude;
    }

    /*!
     * @brief This function returns a reference to member altitude
     * @return Reference to member altitude
     */
    eProsima_user_DllExport double& altitude()
    {
        return m_altitude;
    }



private:

    double m_longitude{0.0};
    double m_latitude{0.0};
    double m_altitude{0.0};

};
/*!
 * @brief This class represents the structure AlarmInfo defined by the user in the IDL file.
 * @ingroup AlarmEvent
 */
class AlarmInfo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport AlarmInfo()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~AlarmInfo()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object AlarmInfo that will be copied.
     */
    eProsima_user_DllExport AlarmInfo(
            const AlarmInfo& x)
    {
                    m_alarmId = x.m_alarmId;

                    m_alarmType = x.m_alarmType;

                    m_status = x.m_status;

                    m_taskStatus = x.m_taskStatus;

                    m_alarmContent = x.m_alarmContent;

                    m_alarmLevel = x.m_alarmLevel;

                    m_areaId = x.m_areaId;

                    m_areaName = x.m_areaName;

                    m_trackId = x.m_trackId;

                    m_classId = x.m_classId;

                    m_behaviorId = x.m_behaviorId;

                    m_position = x.m_position;

                    m_updateTime = x.m_updateTime;

                    m_resolvedTime = x.m_resolvedTime;

                    m_resolvedBy = x.m_resolvedBy;

                    m_resolutionDetails = x.m_resolutionDetails;

                    m_alarmRuleId = x.m_alarmRuleId;

                    m_targetBox = x.m_targetBox;

                    m_track = x.m_track;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object AlarmInfo that will be copied.
     */
    eProsima_user_DllExport AlarmInfo(
            AlarmInfo&& x) noexcept
    {
        m_alarmId = std::move(x.m_alarmId);
        m_alarmType = std::move(x.m_alarmType);
        m_status = x.m_status;
        m_taskStatus = x.m_taskStatus;
        m_alarmContent = std::move(x.m_alarmContent);
        m_alarmLevel = x.m_alarmLevel;
        m_areaId = std::move(x.m_areaId);
        m_areaName = std::move(x.m_areaName);
        m_trackId = std::move(x.m_trackId);
        m_classId = x.m_classId;
        m_behaviorId = x.m_behaviorId;
        m_position = std::move(x.m_position);
        m_updateTime = std::move(x.m_updateTime);
        m_resolvedTime = std::move(x.m_resolvedTime);
        m_resolvedBy = std::move(x.m_resolvedBy);
        m_resolutionDetails = std::move(x.m_resolutionDetails);
        m_alarmRuleId = std::move(x.m_alarmRuleId);
        m_targetBox = std::move(x.m_targetBox);
        m_track = std::move(x.m_track);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object AlarmInfo that will be copied.
     */
    eProsima_user_DllExport AlarmInfo& operator =(
            const AlarmInfo& x)
    {

                    m_alarmId = x.m_alarmId;

                    m_alarmType = x.m_alarmType;

                    m_status = x.m_status;

                    m_taskStatus = x.m_taskStatus;

                    m_alarmContent = x.m_alarmContent;

                    m_alarmLevel = x.m_alarmLevel;

                    m_areaId = x.m_areaId;

                    m_areaName = x.m_areaName;

                    m_trackId = x.m_trackId;

                    m_classId = x.m_classId;

                    m_behaviorId = x.m_behaviorId;

                    m_position = x.m_position;

                    m_updateTime = x.m_updateTime;

                    m_resolvedTime = x.m_resolvedTime;

                    m_resolvedBy = x.m_resolvedBy;

                    m_resolutionDetails = x.m_resolutionDetails;

                    m_alarmRuleId = x.m_alarmRuleId;

                    m_targetBox = x.m_targetBox;

                    m_track = x.m_track;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object AlarmInfo that will be copied.
     */
    eProsima_user_DllExport AlarmInfo& operator =(
            AlarmInfo&& x) noexcept
    {

        m_alarmId = std::move(x.m_alarmId);
        m_alarmType = std::move(x.m_alarmType);
        m_status = x.m_status;
        m_taskStatus = x.m_taskStatus;
        m_alarmContent = std::move(x.m_alarmContent);
        m_alarmLevel = x.m_alarmLevel;
        m_areaId = std::move(x.m_areaId);
        m_areaName = std::move(x.m_areaName);
        m_trackId = std::move(x.m_trackId);
        m_classId = x.m_classId;
        m_behaviorId = x.m_behaviorId;
        m_position = std::move(x.m_position);
        m_updateTime = std::move(x.m_updateTime);
        m_resolvedTime = std::move(x.m_resolvedTime);
        m_resolvedBy = std::move(x.m_resolvedBy);
        m_resolutionDetails = std::move(x.m_resolutionDetails);
        m_alarmRuleId = std::move(x.m_alarmRuleId);
        m_targetBox = std::move(x.m_targetBox);
        m_track = std::move(x.m_track);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x AlarmInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const AlarmInfo& x) const
    {
        return (m_alarmId == x.m_alarmId &&
           m_alarmType == x.m_alarmType &&
           m_status == x.m_status &&
           m_taskStatus == x.m_taskStatus &&
           m_alarmContent == x.m_alarmContent &&
           m_alarmLevel == x.m_alarmLevel &&
           m_areaId == x.m_areaId &&
           m_areaName == x.m_areaName &&
           m_trackId == x.m_trackId &&
           m_classId == x.m_classId &&
           m_behaviorId == x.m_behaviorId &&
           m_position == x.m_position &&
           m_updateTime == x.m_updateTime &&
           m_resolvedTime == x.m_resolvedTime &&
           m_resolvedBy == x.m_resolvedBy &&
           m_resolutionDetails == x.m_resolutionDetails &&
           m_alarmRuleId == x.m_alarmRuleId &&
           m_targetBox == x.m_targetBox &&
           m_track == x.m_track);
    }

    /*!
     * @brief Comparison operator.
     * @param x AlarmInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const AlarmInfo& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member alarmId
     * @param _alarmId New value to be copied in member alarmId
     */
    eProsima_user_DllExport void alarmId(
            const std::string& _alarmId)
    {
        m_alarmId = _alarmId;
    }

    /*!
     * @brief This function moves the value in member alarmId
     * @param _alarmId New value to be moved in member alarmId
     */
    eProsima_user_DllExport void alarmId(
            std::string&& _alarmId)
    {
        m_alarmId = std::move(_alarmId);
    }

    /*!
     * @brief This function returns a constant reference to member alarmId
     * @return Constant reference to member alarmId
     */
    eProsima_user_DllExport const std::string& alarmId() const
    {
        return m_alarmId;
    }

    /*!
     * @brief This function returns a reference to member alarmId
     * @return Reference to member alarmId
     */
    eProsima_user_DllExport std::string& alarmId()
    {
        return m_alarmId;
    }


    /*!
     * @brief This function copies the value in member alarmType
     * @param _alarmType New value to be copied in member alarmType
     */
    eProsima_user_DllExport void alarmType(
            const std::vector<AlarmType>& _alarmType)
    {
        m_alarmType = _alarmType;
    }

    /*!
     * @brief This function moves the value in member alarmType
     * @param _alarmType New value to be moved in member alarmType
     */
    eProsima_user_DllExport void alarmType(
            std::vector<AlarmType>&& _alarmType)
    {
        m_alarmType = std::move(_alarmType);
    }

    /*!
     * @brief This function returns a constant reference to member alarmType
     * @return Constant reference to member alarmType
     */
    eProsima_user_DllExport const std::vector<AlarmType>& alarmType() const
    {
        return m_alarmType;
    }

    /*!
     * @brief This function returns a reference to member alarmType
     * @return Reference to member alarmType
     */
    eProsima_user_DllExport std::vector<AlarmType>& alarmType()
    {
        return m_alarmType;
    }


    /*!
     * @brief This function sets a value in member status
     * @param _status New value for member status
     */
    eProsima_user_DllExport void status(
            AlarmStatus _status)
    {
        m_status = _status;
    }

    /*!
     * @brief This function returns the value of member status
     * @return Value of member status
     */
    eProsima_user_DllExport AlarmStatus status() const
    {
        return m_status;
    }

    /*!
     * @brief This function returns a reference to member status
     * @return Reference to member status
     */
    eProsima_user_DllExport AlarmStatus& status()
    {
        return m_status;
    }


    /*!
     * @brief This function sets a value in member taskStatus
     * @param _taskStatus New value for member taskStatus
     */
    eProsima_user_DllExport void taskStatus(
            AlarmTaskStatus _taskStatus)
    {
        m_taskStatus = _taskStatus;
    }

    /*!
     * @brief This function returns the value of member taskStatus
     * @return Value of member taskStatus
     */
    eProsima_user_DllExport AlarmTaskStatus taskStatus() const
    {
        return m_taskStatus;
    }

    /*!
     * @brief This function returns a reference to member taskStatus
     * @return Reference to member taskStatus
     */
    eProsima_user_DllExport AlarmTaskStatus& taskStatus()
    {
        return m_taskStatus;
    }


    /*!
     * @brief This function copies the value in member alarmContent
     * @param _alarmContent New value to be copied in member alarmContent
     */
    eProsima_user_DllExport void alarmContent(
            const std::string& _alarmContent)
    {
        m_alarmContent = _alarmContent;
    }

    /*!
     * @brief This function moves the value in member alarmContent
     * @param _alarmContent New value to be moved in member alarmContent
     */
    eProsima_user_DllExport void alarmContent(
            std::string&& _alarmContent)
    {
        m_alarmContent = std::move(_alarmContent);
    }

    /*!
     * @brief This function returns a constant reference to member alarmContent
     * @return Constant reference to member alarmContent
     */
    eProsima_user_DllExport const std::string& alarmContent() const
    {
        return m_alarmContent;
    }

    /*!
     * @brief This function returns a reference to member alarmContent
     * @return Reference to member alarmContent
     */
    eProsima_user_DllExport std::string& alarmContent()
    {
        return m_alarmContent;
    }


    /*!
     * @brief This function sets a value in member alarmLevel
     * @param _alarmLevel New value for member alarmLevel
     */
    eProsima_user_DllExport void alarmLevel(
            int32_t _alarmLevel)
    {
        m_alarmLevel = _alarmLevel;
    }

    /*!
     * @brief This function returns the value of member alarmLevel
     * @return Value of member alarmLevel
     */
    eProsima_user_DllExport int32_t alarmLevel() const
    {
        return m_alarmLevel;
    }

    /*!
     * @brief This function returns a reference to member alarmLevel
     * @return Reference to member alarmLevel
     */
    eProsima_user_DllExport int32_t& alarmLevel()
    {
        return m_alarmLevel;
    }


    /*!
     * @brief This function copies the value in member areaId
     * @param _areaId New value to be copied in member areaId
     */
    eProsima_user_DllExport void areaId(
            const std::string& _areaId)
    {
        m_areaId = _areaId;
    }

    /*!
     * @brief This function moves the value in member areaId
     * @param _areaId New value to be moved in member areaId
     */
    eProsima_user_DllExport void areaId(
            std::string&& _areaId)
    {
        m_areaId = std::move(_areaId);
    }

    /*!
     * @brief This function returns a constant reference to member areaId
     * @return Constant reference to member areaId
     */
    eProsima_user_DllExport const std::string& areaId() const
    {
        return m_areaId;
    }

    /*!
     * @brief This function returns a reference to member areaId
     * @return Reference to member areaId
     */
    eProsima_user_DllExport std::string& areaId()
    {
        return m_areaId;
    }


    /*!
     * @brief This function copies the value in member areaName
     * @param _areaName New value to be copied in member areaName
     */
    eProsima_user_DllExport void areaName(
            const std::string& _areaName)
    {
        m_areaName = _areaName;
    }

    /*!
     * @brief This function moves the value in member areaName
     * @param _areaName New value to be moved in member areaName
     */
    eProsima_user_DllExport void areaName(
            std::string&& _areaName)
    {
        m_areaName = std::move(_areaName);
    }

    /*!
     * @brief This function returns a constant reference to member areaName
     * @return Constant reference to member areaName
     */
    eProsima_user_DllExport const std::string& areaName() const
    {
        return m_areaName;
    }

    /*!
     * @brief This function returns a reference to member areaName
     * @return Reference to member areaName
     */
    eProsima_user_DllExport std::string& areaName()
    {
        return m_areaName;
    }


    /*!
     * @brief This function copies the value in member trackId
     * @param _trackId New value to be copied in member trackId
     */
    eProsima_user_DllExport void trackId(
            const std::string& _trackId)
    {
        m_trackId = _trackId;
    }

    /*!
     * @brief This function moves the value in member trackId
     * @param _trackId New value to be moved in member trackId
     */
    eProsima_user_DllExport void trackId(
            std::string&& _trackId)
    {
        m_trackId = std::move(_trackId);
    }

    /*!
     * @brief This function returns a constant reference to member trackId
     * @return Constant reference to member trackId
     */
    eProsima_user_DllExport const std::string& trackId() const
    {
        return m_trackId;
    }

    /*!
     * @brief This function returns a reference to member trackId
     * @return Reference to member trackId
     */
    eProsima_user_DllExport std::string& trackId()
    {
        return m_trackId;
    }


    /*!
     * @brief This function sets a value in member classId
     * @param _classId New value for member classId
     */
    eProsima_user_DllExport void classId(
            int32_t _classId)
    {
        m_classId = _classId;
    }

    /*!
     * @brief This function returns the value of member classId
     * @return Value of member classId
     */
    eProsima_user_DllExport int32_t classId() const
    {
        return m_classId;
    }

    /*!
     * @brief This function returns a reference to member classId
     * @return Reference to member classId
     */
    eProsima_user_DllExport int32_t& classId()
    {
        return m_classId;
    }


    /*!
     * @brief This function sets a value in member behaviorId
     * @param _behaviorId New value for member behaviorId
     */
    eProsima_user_DllExport void behaviorId(
            int32_t _behaviorId)
    {
        m_behaviorId = _behaviorId;
    }

    /*!
     * @brief This function returns the value of member behaviorId
     * @return Value of member behaviorId
     */
    eProsima_user_DllExport int32_t behaviorId() const
    {
        return m_behaviorId;
    }

    /*!
     * @brief This function returns a reference to member behaviorId
     * @return Reference to member behaviorId
     */
    eProsima_user_DllExport int32_t& behaviorId()
    {
        return m_behaviorId;
    }


    /*!
     * @brief This function copies the value in member position
     * @param _position New value to be copied in member position
     */
    eProsima_user_DllExport void position(
            const GeoPosition& _position)
    {
        m_position = _position;
    }

    /*!
     * @brief This function moves the value in member position
     * @param _position New value to be moved in member position
     */
    eProsima_user_DllExport void position(
            GeoPosition&& _position)
    {
        m_position = std::move(_position);
    }

    /*!
     * @brief This function returns a constant reference to member position
     * @return Constant reference to member position
     */
    eProsima_user_DllExport const GeoPosition& position() const
    {
        return m_position;
    }

    /*!
     * @brief This function returns a reference to member position
     * @return Reference to member position
     */
    eProsima_user_DllExport GeoPosition& position()
    {
        return m_position;
    }


    /*!
     * @brief This function copies the value in member updateTime
     * @param _updateTime New value to be copied in member updateTime
     */
    eProsima_user_DllExport void updateTime(
            const std::string& _updateTime)
    {
        m_updateTime = _updateTime;
    }

    /*!
     * @brief This function moves the value in member updateTime
     * @param _updateTime New value to be moved in member updateTime
     */
    eProsima_user_DllExport void updateTime(
            std::string&& _updateTime)
    {
        m_updateTime = std::move(_updateTime);
    }

    /*!
     * @brief This function returns a constant reference to member updateTime
     * @return Constant reference to member updateTime
     */
    eProsima_user_DllExport const std::string& updateTime() const
    {
        return m_updateTime;
    }

    /*!
     * @brief This function returns a reference to member updateTime
     * @return Reference to member updateTime
     */
    eProsima_user_DllExport std::string& updateTime()
    {
        return m_updateTime;
    }


    /*!
     * @brief This function copies the value in member resolvedTime
     * @param _resolvedTime New value to be copied in member resolvedTime
     */
    eProsima_user_DllExport void resolvedTime(
            const std::string& _resolvedTime)
    {
        m_resolvedTime = _resolvedTime;
    }

    /*!
     * @brief This function moves the value in member resolvedTime
     * @param _resolvedTime New value to be moved in member resolvedTime
     */
    eProsima_user_DllExport void resolvedTime(
            std::string&& _resolvedTime)
    {
        m_resolvedTime = std::move(_resolvedTime);
    }

    /*!
     * @brief This function returns a constant reference to member resolvedTime
     * @return Constant reference to member resolvedTime
     */
    eProsima_user_DllExport const std::string& resolvedTime() const
    {
        return m_resolvedTime;
    }

    /*!
     * @brief This function returns a reference to member resolvedTime
     * @return Reference to member resolvedTime
     */
    eProsima_user_DllExport std::string& resolvedTime()
    {
        return m_resolvedTime;
    }


    /*!
     * @brief This function copies the value in member resolvedBy
     * @param _resolvedBy New value to be copied in member resolvedBy
     */
    eProsima_user_DllExport void resolvedBy(
            const std::string& _resolvedBy)
    {
        m_resolvedBy = _resolvedBy;
    }

    /*!
     * @brief This function moves the value in member resolvedBy
     * @param _resolvedBy New value to be moved in member resolvedBy
     */
    eProsima_user_DllExport void resolvedBy(
            std::string&& _resolvedBy)
    {
        m_resolvedBy = std::move(_resolvedBy);
    }

    /*!
     * @brief This function returns a constant reference to member resolvedBy
     * @return Constant reference to member resolvedBy
     */
    eProsima_user_DllExport const std::string& resolvedBy() const
    {
        return m_resolvedBy;
    }

    /*!
     * @brief This function returns a reference to member resolvedBy
     * @return Reference to member resolvedBy
     */
    eProsima_user_DllExport std::string& resolvedBy()
    {
        return m_resolvedBy;
    }


    /*!
     * @brief This function copies the value in member resolutionDetails
     * @param _resolutionDetails New value to be copied in member resolutionDetails
     */
    eProsima_user_DllExport void resolutionDetails(
            const std::string& _resolutionDetails)
    {
        m_resolutionDetails = _resolutionDetails;
    }

    /*!
     * @brief This function moves the value in member resolutionDetails
     * @param _resolutionDetails New value to be moved in member resolutionDetails
     */
    eProsima_user_DllExport void resolutionDetails(
            std::string&& _resolutionDetails)
    {
        m_resolutionDetails = std::move(_resolutionDetails);
    }

    /*!
     * @brief This function returns a constant reference to member resolutionDetails
     * @return Constant reference to member resolutionDetails
     */
    eProsima_user_DllExport const std::string& resolutionDetails() const
    {
        return m_resolutionDetails;
    }

    /*!
     * @brief This function returns a reference to member resolutionDetails
     * @return Reference to member resolutionDetails
     */
    eProsima_user_DllExport std::string& resolutionDetails()
    {
        return m_resolutionDetails;
    }


    /*!
     * @brief This function copies the value in member alarmRuleId
     * @param _alarmRuleId New value to be copied in member alarmRuleId
     */
    eProsima_user_DllExport void alarmRuleId(
            const std::vector<std::string>& _alarmRuleId)
    {
        m_alarmRuleId = _alarmRuleId;
    }

    /*!
     * @brief This function moves the value in member alarmRuleId
     * @param _alarmRuleId New value to be moved in member alarmRuleId
     */
    eProsima_user_DllExport void alarmRuleId(
            std::vector<std::string>&& _alarmRuleId)
    {
        m_alarmRuleId = std::move(_alarmRuleId);
    }

    /*!
     * @brief This function returns a constant reference to member alarmRuleId
     * @return Constant reference to member alarmRuleId
     */
    eProsima_user_DllExport const std::vector<std::string>& alarmRuleId() const
    {
        return m_alarmRuleId;
    }

    /*!
     * @brief This function returns a reference to member alarmRuleId
     * @return Reference to member alarmRuleId
     */
    eProsima_user_DllExport std::vector<std::string>& alarmRuleId()
    {
        return m_alarmRuleId;
    }


    /*!
     * @brief This function copies the value in member targetBox
     * @param _targetBox New value to be copied in member targetBox
     */
    eProsima_user_DllExport void targetBox(
            const BoundingBox& _targetBox)
    {
        m_targetBox = _targetBox;
    }

    /*!
     * @brief This function moves the value in member targetBox
     * @param _targetBox New value to be moved in member targetBox
     */
    eProsima_user_DllExport void targetBox(
            BoundingBox&& _targetBox)
    {
        m_targetBox = std::move(_targetBox);
    }

    /*!
     * @brief This function returns a constant reference to member targetBox
     * @return Constant reference to member targetBox
     */
    eProsima_user_DllExport const BoundingBox& targetBox() const
    {
        return m_targetBox;
    }

    /*!
     * @brief This function returns a reference to member targetBox
     * @return Reference to member targetBox
     */
    eProsima_user_DllExport BoundingBox& targetBox()
    {
        return m_targetBox;
    }


    /*!
     * @brief This function copies the value in member track
     * @param _track New value to be copied in member track
     */
    eProsima_user_DllExport void track(
            const TrackData& _track)
    {
        m_track = _track;
    }

    /*!
     * @brief This function moves the value in member track
     * @param _track New value to be moved in member track
     */
    eProsima_user_DllExport void track(
            TrackData&& _track)
    {
        m_track = std::move(_track);
    }

    /*!
     * @brief This function returns a constant reference to member track
     * @return Constant reference to member track
     */
    eProsima_user_DllExport const TrackData& track() const
    {
        return m_track;
    }

    /*!
     * @brief This function returns a reference to member track
     * @return Reference to member track
     */
    eProsima_user_DllExport TrackData& track()
    {
        return m_track;
    }



private:

    std::string m_alarmId;
    std::vector<AlarmType> m_alarmType;
    AlarmStatus m_status{AlarmStatus::ACTIVE};
    AlarmTaskStatus m_taskStatus{AlarmTaskStatus::UNASSIGNED};
    std::string m_alarmContent;
    int32_t m_alarmLevel{0};
    std::string m_areaId;
    std::string m_areaName;
    std::string m_trackId;
    int32_t m_classId{0};
    int32_t m_behaviorId{0};
    GeoPosition m_position;
    std::string m_updateTime;
    std::string m_resolvedTime;
    std::string m_resolvedBy;
    std::string m_resolutionDetails;
    std::vector<std::string> m_alarmRuleId;
    BoundingBox m_targetBox;
    TrackData m_track;

};
/*!
 * @brief This class represents the structure AlarmEvent defined by the user in the IDL file.
 * @ingroup AlarmEvent
 */
class AlarmEvent : public casia::event::BaseEvent
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport AlarmEvent()
        : casia::event::BaseEvent()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~AlarmEvent()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object AlarmEvent that will be copied.
     */
    eProsima_user_DllExport AlarmEvent(
            const AlarmEvent& x)
        : casia::event::BaseEvent(x)
    {
                    m_alarm = x.m_alarm;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object AlarmEvent that will be copied.
     */
    eProsima_user_DllExport AlarmEvent(
            AlarmEvent&& x) noexcept
        : casia::event::BaseEvent(std::move(x))

    {
        m_alarm = std::move(x.m_alarm);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object AlarmEvent that will be copied.
     */
    eProsima_user_DllExport AlarmEvent& operator =(
            const AlarmEvent& x)
    {
        casia::event::BaseEvent::operator =(x);

                    m_alarm = x.m_alarm;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object AlarmEvent that will be copied.
     */
    eProsima_user_DllExport AlarmEvent& operator =(
            AlarmEvent&& x) noexcept
    {
        casia::event::BaseEvent::operator =(std::move(x));

        m_alarm = std::move(x.m_alarm);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x AlarmEvent object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const AlarmEvent& x) const
    {
        if (casia::event::BaseEvent::operator !=(x))
                {
                    return false;
                }
        return (m_alarm == x.m_alarm);
    }

    /*!
     * @brief Comparison operator.
     * @param x AlarmEvent object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const AlarmEvent& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member alarm
     * @param _alarm New value to be copied in member alarm
     */
    eProsima_user_DllExport void alarm(
            const std::vector<AlarmInfo>& _alarm)
    {
        m_alarm = _alarm;
    }

    /*!
     * @brief This function moves the value in member alarm
     * @param _alarm New value to be moved in member alarm
     */
    eProsima_user_DllExport void alarm(
            std::vector<AlarmInfo>&& _alarm)
    {
        m_alarm = std::move(_alarm);
    }

    /*!
     * @brief This function returns a constant reference to member alarm
     * @return Constant reference to member alarm
     */
    eProsima_user_DllExport const std::vector<AlarmInfo>& alarm() const
    {
        return m_alarm;
    }

    /*!
     * @brief This function returns a reference to member alarm
     * @return Reference to member alarm
     */
    eProsima_user_DllExport std::vector<AlarmInfo>& alarm()
    {
        return m_alarm;
    }



private:

    std::vector<AlarmInfo> m_alarm;

};

} // namespace alarm

} // namespace event

} // namespace casia

#endif // _FAST_DDS_GENERATED_CASIA_EVENT_ALARM_ALARMEVENT_HPP_


