// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AlarmEventPublisherApp.cxx
 * This file contains the implementation of the publisher functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "AlarmEventPublisherApp.hpp"

#include "dialog/alarm/AlarmFileLogger.h"

#include <chrono>
#include <condition_variable>
#include <csignal>
#include <map>
#include <mutex>
#include <stdexcept>
#include <thread>

#include <QSettings>
#include <QString>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/publisher/qos/DataWriterQos.hpp>
#include <fastdds/dds/publisher/qos/PublisherQos.hpp>

#include "AlarmEventPubSubTypes.hpp"

using namespace eprosima::fastdds::dds;

namespace {
struct AlarmEventDdsConfig {
    bool useProfile = true;
    QString xmlMulti = QStringLiteral("alarmevent_multi.xml");
    QString profileMulti = QStringLiteral("participant_alarmevent");
    QString xmlSingle = QStringLiteral("alarmevent_single.xml");
    QString profileSingle = QStringLiteral("participant_alarmevent_single");
    QString topicName = QStringLiteral("AlarmEventTopic");
};

AlarmEventDdsConfig loadAlarmEventDdsConfig()
{
    AlarmEventDdsConfig c;
    QSettings s(QStringLiteral("Config.ini"), QSettings::IniFormat);
    c.useProfile = s.value(QStringLiteral("DDS/AlarmEventUseProfile"), 1).toInt() != 0;
    c.xmlMulti = s.value(QStringLiteral("DDS/AlarmEventXmlMulti"),
        s.value(QStringLiteral("DDS/AlarmEventXml"), c.xmlMulti)).toString();
    c.profileMulti = s.value(QStringLiteral("DDS/AlarmEventParticipantProfileMulti"),
        s.value(QStringLiteral("DDS/AlarmEventParticipantProfile"), c.profileMulti)).toString();
    c.xmlSingle = s.value(QStringLiteral("DDS/AlarmEventXmlSingle"), c.xmlSingle).toString();
    c.profileSingle = s.value(QStringLiteral("DDS/AlarmEventParticipantProfileSingle"), c.profileSingle).toString();
    c.topicName = s.value(QStringLiteral("DDS/AlarmEventTopic"), c.topicName).toString();
    return c;
}

QString publisherTag(int mode)
{
    return (mode == 0) ? QStringLiteral("multi") : QStringLiteral("single");
}

std::mutex& ddsLogThrottleMutex()
{
    static std::mutex m;
    return m;
}

std::map<QString, qint64>& ddsLogThrottleMap()
{
    static std::map<QString, qint64> map;
    return map;
}

void logDdsEvent(const QString& line, bool force = false)
{
    AlarmFileLogger::logAlarmEventDds(line);
    if (force) {
        std::cout << line.toStdString() << std::endl;
    }
}

void logDdsEventThrottled(const QString& key, const QString& line, qint64 intervalMs = 60000)
{
    const auto nowMs = std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::steady_clock::now().time_since_epoch()).count();
    const qint64 now = static_cast<qint64>(nowMs);
    {
        std::lock_guard<std::mutex> lock(ddsLogThrottleMutex());
        const auto it = ddsLogThrottleMap().find(key);
        if (it != ddsLogThrottleMap().end() && (now - it->second) < intervalMs) {
            return;
        }
        ddsLogThrottleMap()[key] = now;
    }
    logDdsEvent(line, false);
}

/** 从毫秒构造 Duration_t */
Duration_t durationFromMs(int64_t ms)
{
    if (ms < 1) {
        ms = 1;
    }
    return Duration_t(static_cast<int32_t>(ms / 1000), static_cast<uint32_t>((ms % 1000) * 1000000));
}

/** MANUAL liveliness：lease 须大于 announcement_period（Fast DDS QoS 校验） */
void applyManualLivelinessQos(DataWriterQos& writer_qos, uint32_t periodMs)
{
    const int64_t announceMs = std::max<int64_t>(100, static_cast<int64_t>(periodMs) / 2);
    const int64_t leaseMs = std::max<int64_t>(announceMs + 1000, static_cast<int64_t>(periodMs) * 3);
    writer_qos.liveliness().kind = LivelinessQosPolicyKind::MANUAL_BY_PARTICIPANT_LIVELINESS_QOS;
    writer_qos.liveliness().announcement_period = durationFromMs(announceMs);
    writer_qos.liveliness().lease_duration = durationFromMs(leaseMs);
}
} // namespace

AlarmEventPublisherApp::AlarmEventPublisherApp(
    const int& domain_id, int mode)
    : factory_(nullptr)
    , participant_(nullptr)
    , publisher_(nullptr)
    , topic_(nullptr)
    , writer_(nullptr)
    , type_(new casia::event::alarm::AlarmEventPubSubType())
    , matched_(0)
    , samples_sent_(0)
    , stop_(false)
    , m_nMode(mode)
    , m_domainId(domain_id)
{
    const AlarmEventDdsConfig ddsCfg = loadAlarmEventDdsConfig();
    const QString xmlFile = (mode == 0) ? ddsCfg.xmlMulti : ddsCfg.xmlSingle;
    const QString participantProfile = (mode == 0) ? ddsCfg.profileMulti : ddsCfg.profileSingle;
    DomainParticipantQos pqos = PARTICIPANT_QOS_DEFAULT;
    pqos.name("casia::event::alarm::AlarmEvent_pub_participant");
    factory_ = DomainParticipantFactory::get_shared_instance();
    if (ddsCfg.useProfile) {
        factory_->load_XML_profiles_file(xmlFile.toStdString());
        participant_ = factory_->create_participant_with_profile(domain_id, participantProfile.toStdString());
    } else {
        participant_ = factory_->create_participant(domain_id, pqos, nullptr, StatusMask::none());
    }
    if (participant_ == nullptr)
    {
        throw std::runtime_error("casia::event::alarm::AlarmEvent Participant initialization failed");
    }

    type_.register_type(participant_);

    PublisherQos pub_qos = PUBLISHER_QOS_DEFAULT;
    participant_->get_default_publisher_qos(pub_qos);
    publisher_ = participant_->create_publisher(pub_qos, nullptr, StatusMask::none());
    if (publisher_ == nullptr)
    {
        throw std::runtime_error("casia::event::alarm::AlarmEvent Publisher initialization failed");
    }

    TopicQos topic_qos = TOPIC_QOS_DEFAULT;
    participant_->get_default_topic_qos(topic_qos);
    topic_ = participant_->create_topic(ddsCfg.topicName.toStdString(), type_.get_type_name(), topic_qos);
    if (topic_ == nullptr)
    {
        throw std::runtime_error("casia::event::alarm::AlarmEvent Topic initialization failed");
    }

    DataWriterQos writer_qos = DATAWRITER_QOS_DEFAULT;
    publisher_->get_default_datawriter_qos(writer_qos);
    writer_qos.reliability().kind = ReliabilityQosPolicyKind::RELIABLE_RELIABILITY_QOS;
    writer_qos.durability().kind = DurabilityQosPolicyKind::TRANSIENT_LOCAL_DURABILITY_QOS;
    writer_qos.history().kind = HistoryQosPolicyKind::KEEP_LAST_HISTORY_QOS;
    writer_qos.history().depth = 32;
    applyManualLivelinessQos(writer_qos, period_ms_);
    writer_ = publisher_->create_datawriter(topic_, writer_qos, this, StatusMask::all());
    if (writer_ == nullptr)
    {
        throw std::runtime_error("casia::event::alarm::AlarmEvent DataWriter initialization failed");
    }

    logDdsEvent(
        QStringLiteral("[init] tag=%1 domain=%2 topic=%3 xml=%4 profile=%5 period_ms=%6 announce_ms=%7 lease_ms=%8")
            .arg(publisherTag(m_nMode))
            .arg(m_domainId)
            .arg(ddsCfg.topicName)
            .arg(xmlFile)
            .arg(participantProfile)
            .arg(period_ms_)
            .arg(std::max<int64_t>(100, static_cast<int64_t>(period_ms_) / 2))
            .arg(std::max<int64_t>(1000, static_cast<int64_t>(period_ms_) * 3)),
        true);
}

AlarmEventPublisherApp::~AlarmEventPublisherApp()
{
    if (nullptr != participant_)
    {
        participant_->delete_contained_entities();

        if (factory_)
            factory_->delete_participant(participant_);
        else
            DomainParticipantFactory::get_instance()->delete_participant(participant_);
    }
}

void AlarmEventPublisherApp::on_publication_matched(
    DataWriter* /*writer*/,
    const PublicationMatchedStatus& info)
{
    {
        std::lock_guard<std::mutex> lock(mutex_);
        matched_ = info.current_count;
    }
    const QString tag = publisherTag(m_nMode);
    if (info.current_count_change > 0)
    {
        const QString line = QStringLiteral("[matched] tag=%1 domain=%2 count=%3 change=+%4")
            .arg(tag).arg(m_domainId).arg(info.current_count).arg(info.current_count_change);
        logDdsEvent(line, true);
        std::cout << "casia::event::alarm::AlarmEvent Publisher matched (count="
            << info.current_count << ")." << std::endl;
    }
    else if (info.current_count_change < 0)
    {
        const QString line = QStringLiteral("[unmatched] tag=%1 domain=%2 count=%3 change=%4")
            .arg(tag).arg(m_domainId).arg(info.current_count).arg(info.current_count_change);
        logDdsEvent(line, true);
        std::cout << "casia::event::alarm::AlarmEvent Publisher unmatched (count="
            << info.current_count << ")." << std::endl;
    }
    cv_.notify_one();
}

void AlarmEventPublisherApp::run()
{
    logDdsEvent(
        QStringLiteral("[run] tag=%1 domain=%2 thread_started period_ms=%3")
            .arg(publisherTag(m_nMode))
            .arg(m_domainId)
            .arg(period_ms_),
        true);

    while (!is_stopped())
    {
        if (publish())
        {
            ++samples_sent_;
            logDdsEventThrottled(
                QStringLiteral("sent_%1").arg(publisherTag(m_nMode)),
                QStringLiteral("[sent] tag=%1 domain=%2 samples=%3 matched=%4")
                    .arg(publisherTag(m_nMode))
                    .arg(m_domainId)
                    .arg(samples_sent_)
                    .arg(matched_),
                60000);
            std::cout << "Sample '" << std::to_string(samples_sent_) << "' SENT" << std::endl;
        }

        std::unique_lock<std::mutex> period_lock(mutex_);
        cv_.wait_for(period_lock, std::chrono::milliseconds(period_ms_), [this]()
            {
                return is_stopped();
            });
    }

    logDdsEvent(
        QStringLiteral("[run] tag=%1 domain=%2 thread_stopped samples=%3")
            .arg(publisherTag(m_nMode))
            .arg(m_domainId)
            .arg(samples_sent_),
        true);
}

bool AlarmEventPublisherApp::publish()
{
    if (is_stopped() || writer_ == nullptr)
    {
        return false;
    }

    bool livelinessOk = true;
    if (participant_ != nullptr)
    {
        const ReturnCode_t lv = participant_->assert_liveliness();
        livelinessOk = (lv == RETCODE_OK);
        if (!livelinessOk) {
            logDdsEventThrottled(
                QStringLiteral("liveliness_fail_%1").arg(publisherTag(m_nMode)),
                QStringLiteral("[liveliness_fail] tag=%1 domain=%2 code=%3")
                    .arg(publisherTag(m_nMode))
                    .arg(m_domainId)
                    .arg(static_cast<int>(lv)),
                30000);
        }
    }

    casia::event::alarm::AlarmEvent sample;
    int32_t matched_count = 0;
    {
        std::lock_guard<std::mutex> lock(mutex_);
        matched_count = matched_;
        sample = m_curAlarm;
    }

    const int alarmCount = static_cast<int>(sample.alarm().size());
    logDdsEventThrottled(
        QStringLiteral("status_%1").arg(publisherTag(m_nMode)),
        QStringLiteral("[status] tag=%1 domain=%2 matched=%3 alarm_count=%4 liveliness_ok=%5")
            .arg(publisherTag(m_nMode))
            .arg(m_domainId)
            .arg(matched_count)
            .arg(alarmCount)
            .arg(livelinessOk ? 1 : 0),
        60000);

    if (matched_count <= 0)
    {
        logDdsEventThrottled(
            QStringLiteral("skip_nomatch_%1").arg(publisherTag(m_nMode)),
            QStringLiteral("[skip] tag=%1 domain=%2 reason=no_subscriber alarm_count=%3")
                .arg(publisherTag(m_nMode))
                .arg(m_domainId)
                .arg(alarmCount),
            60000);
        return false;
    }

    if (alarmCount <= 0)
    {
        return false;
    }

    const ReturnCode_t wc = writer_->write(&sample);
    if (wc != RETCODE_OK)
    {
        logDdsEvent(
            QStringLiteral("[write_fail] tag=%1 domain=%2 code=%3 alarm_count=%4")
                .arg(publisherTag(m_nMode))
                .arg(m_domainId)
                .arg(static_cast<int>(wc))
                .arg(alarmCount),
            true);
        return false;
    }

    return true;
}

bool AlarmEventPublisherApp::is_stopped()
{
    return stop_.load();
}

void AlarmEventPublisherApp::stop()
{
    stop_.store(true);
    cv_.notify_one();
}

bool AlarmEventPublisherApp::sendLst(AlarmEvent msg)
{
    std::lock_guard<std::mutex> lock(mutex_);
    m_curAlarm = std::move(msg);
    return true;
}

bool AlarmEventPublisherApp::sendNewAlarm(AlarmEvent msg)
{
    if (writer_ == nullptr)
    {
        return false;
    }
    if (participant_ != nullptr)
    {
        participant_->assert_liveliness();
    }

    int32_t matched_count = 0;
    {
        std::lock_guard<std::mutex> lock(mutex_);
        matched_count = matched_;
    }

    const ReturnCode_t wc = writer_->write(&msg);
    if (wc == RETCODE_OK)
    {
        logDdsEvent(
            QStringLiteral("[sendNewAlarm] tag=%1 domain=%2 matched=%3 alarm_count=%4")
                .arg(publisherTag(m_nMode))
                .arg(m_domainId)
                .arg(matched_count)
                .arg(static_cast<int>(msg.alarm().size())),
            false);
        return true;
    }

    logDdsEvent(
        QStringLiteral("[sendNewAlarm_fail] tag=%1 domain=%2 code=%3")
            .arg(publisherTag(m_nMode))
            .arg(m_domainId)
            .arg(static_cast<int>(wc)),
        true);
    return false;
}
