// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BaseEventTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "BaseEventTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "BaseEvent.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace casia {
namespace event {
void register_EventSeverity_type_identifier(
        TypeIdentifierPair& type_ids_EventSeverity)
{
    ReturnCode_t return_code_EventSeverity {eprosima::fastdds::dds::RETCODE_OK};
    return_code_EventSeverity =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "casia::event::EventSeverity", type_ids_EventSeverity);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_EventSeverity)
    {
        EnumTypeFlag enum_flags_EventSeverity = 0;
        BitBound bit_bound_EventSeverity = 32;
        CommonEnumeratedHeader common_EventSeverity = TypeObjectUtils::build_common_enumerated_header(bit_bound_EventSeverity);
        QualifiedTypeName type_name_EventSeverity = "casia::event::EventSeverity";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_EventSeverity;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_EventSeverity;
        CompleteTypeDetail detail_EventSeverity = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_EventSeverity, ann_custom_EventSeverity, type_name_EventSeverity.to_string());
        CompleteEnumeratedHeader header_EventSeverity = TypeObjectUtils::build_complete_enumerated_header(common_EventSeverity, detail_EventSeverity);
        CompleteEnumeratedLiteralSeq literal_seq_EventSeverity;
        {
            EnumeratedLiteralFlag flags_INFO = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_INFO = TypeObjectUtils::build_common_enumerated_literal(0, flags_INFO);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_INFO;
            ann_custom_EventSeverity.reset();
            MemberName name_INFO = "INFO";
            CompleteMemberDetail detail_INFO = TypeObjectUtils::build_complete_member_detail(name_INFO, member_ann_builtin_INFO, ann_custom_EventSeverity);
            CompleteEnumeratedLiteral literal_INFO = TypeObjectUtils::build_complete_enumerated_literal(common_INFO, detail_INFO);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_EventSeverity, literal_INFO);
        }
        {
            EnumeratedLiteralFlag flags_WARNING = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_WARNING = TypeObjectUtils::build_common_enumerated_literal(1, flags_WARNING);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_WARNING;
            ann_custom_EventSeverity.reset();
            MemberName name_WARNING = "WARNING";
            CompleteMemberDetail detail_WARNING = TypeObjectUtils::build_complete_member_detail(name_WARNING, member_ann_builtin_WARNING, ann_custom_EventSeverity);
            CompleteEnumeratedLiteral literal_WARNING = TypeObjectUtils::build_complete_enumerated_literal(common_WARNING, detail_WARNING);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_EventSeverity, literal_WARNING);
        }
        {
            EnumeratedLiteralFlag flags_ERROR_ = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_ERROR_ = TypeObjectUtils::build_common_enumerated_literal(2, flags_ERROR_);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ERROR_;
            ann_custom_EventSeverity.reset();
            MemberName name_ERROR_ = "ERROR_";
            CompleteMemberDetail detail_ERROR_ = TypeObjectUtils::build_complete_member_detail(name_ERROR_, member_ann_builtin_ERROR_, ann_custom_EventSeverity);
            CompleteEnumeratedLiteral literal_ERROR_ = TypeObjectUtils::build_complete_enumerated_literal(common_ERROR_, detail_ERROR_);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_EventSeverity, literal_ERROR_);
        }
        {
            EnumeratedLiteralFlag flags_CRITICAL = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_CRITICAL = TypeObjectUtils::build_common_enumerated_literal(3, flags_CRITICAL);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_CRITICAL;
            ann_custom_EventSeverity.reset();
            MemberName name_CRITICAL = "CRITICAL";
            CompleteMemberDetail detail_CRITICAL = TypeObjectUtils::build_complete_member_detail(name_CRITICAL, member_ann_builtin_CRITICAL, ann_custom_EventSeverity);
            CompleteEnumeratedLiteral literal_CRITICAL = TypeObjectUtils::build_complete_enumerated_literal(common_CRITICAL, detail_CRITICAL);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_EventSeverity, literal_CRITICAL);
        }
        CompleteEnumeratedType enumerated_type_EventSeverity = TypeObjectUtils::build_complete_enumerated_type(enum_flags_EventSeverity, header_EventSeverity,
                literal_seq_EventSeverity);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_enumerated_type_object(enumerated_type_EventSeverity, type_name_EventSeverity.to_string(), type_ids_EventSeverity))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "casia::event::EventSeverity already registered in TypeObjectRegistry for a different type.");
        }
    }
}void register_EventSourceType_type_identifier(
        TypeIdentifierPair& type_ids_EventSourceType)
{
    ReturnCode_t return_code_EventSourceType {eprosima::fastdds::dds::RETCODE_OK};
    return_code_EventSourceType =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "casia::event::EventSourceType", type_ids_EventSourceType);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_EventSourceType)
    {
        EnumTypeFlag enum_flags_EventSourceType = 0;
        BitBound bit_bound_EventSourceType = 32;
        CommonEnumeratedHeader common_EventSourceType = TypeObjectUtils::build_common_enumerated_header(bit_bound_EventSourceType);
        QualifiedTypeName type_name_EventSourceType = "casia::event::EventSourceType";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_EventSourceType;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_EventSourceType;
        CompleteTypeDetail detail_EventSourceType = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_EventSourceType, ann_custom_EventSourceType, type_name_EventSourceType.to_string());
        CompleteEnumeratedHeader header_EventSourceType = TypeObjectUtils::build_complete_enumerated_header(common_EventSourceType, detail_EventSourceType);
        CompleteEnumeratedLiteralSeq literal_seq_EventSourceType;
        {
            EnumeratedLiteralFlag flags_SYSTEM = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_SYSTEM = TypeObjectUtils::build_common_enumerated_literal(0, flags_SYSTEM);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_SYSTEM;
            ann_custom_EventSourceType.reset();
            MemberName name_SYSTEM = "SYSTEM";
            CompleteMemberDetail detail_SYSTEM = TypeObjectUtils::build_complete_member_detail(name_SYSTEM, member_ann_builtin_SYSTEM, ann_custom_EventSourceType);
            CompleteEnumeratedLiteral literal_SYSTEM = TypeObjectUtils::build_complete_enumerated_literal(common_SYSTEM, detail_SYSTEM);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_EventSourceType, literal_SYSTEM);
        }
        {
            EnumeratedLiteralFlag flags_DEVICE = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_DEVICE = TypeObjectUtils::build_common_enumerated_literal(1, flags_DEVICE);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_DEVICE;
            ann_custom_EventSourceType.reset();
            MemberName name_DEVICE = "DEVICE";
            CompleteMemberDetail detail_DEVICE = TypeObjectUtils::build_complete_member_detail(name_DEVICE, member_ann_builtin_DEVICE, ann_custom_EventSourceType);
            CompleteEnumeratedLiteral literal_DEVICE = TypeObjectUtils::build_complete_enumerated_literal(common_DEVICE, detail_DEVICE);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_EventSourceType, literal_DEVICE);
        }
        {
            EnumeratedLiteralFlag flags_USER = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_USER = TypeObjectUtils::build_common_enumerated_literal(2, flags_USER);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_USER;
            ann_custom_EventSourceType.reset();
            MemberName name_USER = "USER";
            CompleteMemberDetail detail_USER = TypeObjectUtils::build_complete_member_detail(name_USER, member_ann_builtin_USER, ann_custom_EventSourceType);
            CompleteEnumeratedLiteral literal_USER = TypeObjectUtils::build_complete_enumerated_literal(common_USER, detail_USER);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_EventSourceType, literal_USER);
        }
        {
            EnumeratedLiteralFlag flags_TASK = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_TASK = TypeObjectUtils::build_common_enumerated_literal(3, flags_TASK);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_TASK;
            ann_custom_EventSourceType.reset();
            MemberName name_TASK = "TASK";
            CompleteMemberDetail detail_TASK = TypeObjectUtils::build_complete_member_detail(name_TASK, member_ann_builtin_TASK, ann_custom_EventSourceType);
            CompleteEnumeratedLiteral literal_TASK = TypeObjectUtils::build_complete_enumerated_literal(common_TASK, detail_TASK);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_EventSourceType, literal_TASK);
        }
        {
            EnumeratedLiteralFlag flags_TRACK = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_TRACK = TypeObjectUtils::build_common_enumerated_literal(4, flags_TRACK);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_TRACK;
            ann_custom_EventSourceType.reset();
            MemberName name_TRACK = "TRACK";
            CompleteMemberDetail detail_TRACK = TypeObjectUtils::build_complete_member_detail(name_TRACK, member_ann_builtin_TRACK, ann_custom_EventSourceType);
            CompleteEnumeratedLiteral literal_TRACK = TypeObjectUtils::build_complete_enumerated_literal(common_TRACK, detail_TRACK);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_EventSourceType, literal_TRACK);
        }
        CompleteEnumeratedType enumerated_type_EventSourceType = TypeObjectUtils::build_complete_enumerated_type(enum_flags_EventSourceType, header_EventSourceType,
                literal_seq_EventSourceType);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_enumerated_type_object(enumerated_type_EventSourceType, type_name_EventSourceType.to_string(), type_ids_EventSourceType))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "casia::event::EventSourceType already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_BaseEvent_type_identifier(
        TypeIdentifierPair& type_ids_BaseEvent)
{

    ReturnCode_t return_code_BaseEvent {eprosima::fastdds::dds::RETCODE_OK};
    return_code_BaseEvent =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "casia::event::BaseEvent", type_ids_BaseEvent);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_BaseEvent)
    {
        StructTypeFlag struct_flags_BaseEvent = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_BaseEvent = "casia::event::BaseEvent";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_BaseEvent;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_BaseEvent;
        CompleteTypeDetail detail_BaseEvent = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_BaseEvent, ann_custom_BaseEvent, type_name_BaseEvent.to_string());
        CompleteStructHeader header_BaseEvent;
        header_BaseEvent = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_BaseEvent);
        CompleteStructMemberSeq member_seq_BaseEvent;
        {
            TypeIdentifierPair type_ids_eventId;
            ReturnCode_t return_code_eventId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_eventId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_eventId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_eventId)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_eventId))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_eventId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_eventId = 0x00000000;
            bool common_eventId_ec {false};
            CommonStructMember common_eventId {TypeObjectUtils::build_common_struct_member(member_id_eventId, member_flags_eventId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_eventId, common_eventId_ec))};
            if (!common_eventId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure eventId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_eventId = "eventId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_eventId;
            ann_custom_BaseEvent.reset();
            CompleteMemberDetail detail_eventId = TypeObjectUtils::build_complete_member_detail(name_eventId, member_ann_builtin_eventId, ann_custom_BaseEvent);
            CompleteStructMember member_eventId = TypeObjectUtils::build_complete_struct_member(common_eventId, detail_eventId);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseEvent, member_eventId);
        }
        {
            TypeIdentifierPair type_ids_sourceId;
            ReturnCode_t return_code_sourceId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_sourceId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_sourceId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_sourceId)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_sourceId))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_sourceId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_sourceId = 0x00000001;
            bool common_sourceId_ec {false};
            CommonStructMember common_sourceId {TypeObjectUtils::build_common_struct_member(member_id_sourceId, member_flags_sourceId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_sourceId, common_sourceId_ec))};
            if (!common_sourceId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure sourceId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_sourceId = "sourceId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_sourceId;
            ann_custom_BaseEvent.reset();
            CompleteMemberDetail detail_sourceId = TypeObjectUtils::build_complete_member_detail(name_sourceId, member_ann_builtin_sourceId, ann_custom_BaseEvent);
            CompleteStructMember member_sourceId = TypeObjectUtils::build_complete_struct_member(common_sourceId, detail_sourceId);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseEvent, member_sourceId);
        }
        {
            TypeIdentifierPair type_ids_sourceType;
            ReturnCode_t return_code_sourceType {eprosima::fastdds::dds::RETCODE_OK};
            return_code_sourceType =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "casia::event::EventSourceType", type_ids_sourceType);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_sourceType)
            {
                casia::event::register_EventSourceType_type_identifier(type_ids_sourceType);
            }
            StructMemberFlag member_flags_sourceType = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_sourceType = 0x00000002;
            bool common_sourceType_ec {false};
            CommonStructMember common_sourceType {TypeObjectUtils::build_common_struct_member(member_id_sourceType, member_flags_sourceType, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_sourceType, common_sourceType_ec))};
            if (!common_sourceType_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure sourceType member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_sourceType = "sourceType";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_sourceType;
            ann_custom_BaseEvent.reset();
            CompleteMemberDetail detail_sourceType = TypeObjectUtils::build_complete_member_detail(name_sourceType, member_ann_builtin_sourceType, ann_custom_BaseEvent);
            CompleteStructMember member_sourceType = TypeObjectUtils::build_complete_struct_member(common_sourceType, detail_sourceType);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseEvent, member_sourceType);
        }
        {
            TypeIdentifierPair type_ids_severity;
            ReturnCode_t return_code_severity {eprosima::fastdds::dds::RETCODE_OK};
            return_code_severity =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "casia::event::EventSeverity", type_ids_severity);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_severity)
            {
                casia::event::register_EventSeverity_type_identifier(type_ids_severity);
            }
            StructMemberFlag member_flags_severity = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_severity = 0x00000003;
            bool common_severity_ec {false};
            CommonStructMember common_severity {TypeObjectUtils::build_common_struct_member(member_id_severity, member_flags_severity, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_severity, common_severity_ec))};
            if (!common_severity_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure severity member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_severity = "severity";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_severity;
            ann_custom_BaseEvent.reset();
            CompleteMemberDetail detail_severity = TypeObjectUtils::build_complete_member_detail(name_severity, member_ann_builtin_severity, ann_custom_BaseEvent);
            CompleteStructMember member_severity = TypeObjectUtils::build_complete_struct_member(common_severity, detail_severity);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseEvent, member_severity);
        }
        {
            TypeIdentifierPair type_ids_message;
            ReturnCode_t return_code_message {eprosima::fastdds::dds::RETCODE_OK};
            return_code_message =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_message);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_message)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_message))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_message = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_message = 0x00000004;
            bool common_message_ec {false};
            CommonStructMember common_message {TypeObjectUtils::build_common_struct_member(member_id_message, member_flags_message, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_message, common_message_ec))};
            if (!common_message_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure message member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_message = "message";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_message;
            ann_custom_BaseEvent.reset();
            CompleteMemberDetail detail_message = TypeObjectUtils::build_complete_member_detail(name_message, member_ann_builtin_message, ann_custom_BaseEvent);
            CompleteStructMember member_message = TypeObjectUtils::build_complete_struct_member(common_message, detail_message);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseEvent, member_message);
        }
        {
            TypeIdentifierPair type_ids_timestamp;
            ReturnCode_t return_code_timestamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_timestamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_timestamp))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_timestamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp = 0x00000005;
            bool common_timestamp_ec {false};
            CommonStructMember common_timestamp {TypeObjectUtils::build_common_struct_member(member_id_timestamp, member_flags_timestamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp, common_timestamp_ec))};
            if (!common_timestamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp = "timestamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp;
            ann_custom_BaseEvent.reset();
            CompleteMemberDetail detail_timestamp = TypeObjectUtils::build_complete_member_detail(name_timestamp, member_ann_builtin_timestamp, ann_custom_BaseEvent);
            CompleteStructMember member_timestamp = TypeObjectUtils::build_complete_struct_member(common_timestamp, detail_timestamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseEvent, member_timestamp);
        }
        {
            TypeIdentifierPair type_ids_userId;
            ReturnCode_t return_code_userId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_userId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_userId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_userId)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_userId))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_userId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_userId = 0x00000006;
            bool common_userId_ec {false};
            CommonStructMember common_userId {TypeObjectUtils::build_common_struct_member(member_id_userId, member_flags_userId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_userId, common_userId_ec))};
            if (!common_userId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure userId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_userId = "userId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_userId;
            ann_custom_BaseEvent.reset();
            CompleteMemberDetail detail_userId = TypeObjectUtils::build_complete_member_detail(name_userId, member_ann_builtin_userId, ann_custom_BaseEvent);
            CompleteStructMember member_userId = TypeObjectUtils::build_complete_struct_member(common_userId, detail_userId);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseEvent, member_userId);
        }
        {
            TypeIdentifierPair type_ids_deviceId;
            ReturnCode_t return_code_deviceId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_deviceId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_anonymous_string_unbounded_unbounded", type_ids_deviceId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_deviceId)
            {
                return_code_deviceId =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "anonymous_string_unbounded", type_ids_deviceId);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_deviceId)
                {
                    {
                        SBound bound = 0;
                        StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                                TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                                "anonymous_string_unbounded", type_ids_deviceId))
                        {
                            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                                "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                        }
                    }
                }
                bool element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_deviceId, element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_anonymous_string_unbounded_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_deviceId.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_anonymous_string_unbounded_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_anonymous_string_unbounded_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_anonymous_string_unbounded_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_anonymous_string_unbounded_unbounded, element_flags_anonymous_sequence_anonymous_string_unbounded_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_anonymous_string_unbounded_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_anonymous_string_unbounded_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_anonymous_string_unbounded_unbounded", type_ids_deviceId))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_anonymous_string_unbounded_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_deviceId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_deviceId = 0x00000007;
            bool common_deviceId_ec {false};
            CommonStructMember common_deviceId {TypeObjectUtils::build_common_struct_member(member_id_deviceId, member_flags_deviceId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_deviceId, common_deviceId_ec))};
            if (!common_deviceId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure deviceId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_deviceId = "deviceId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_deviceId;
            ann_custom_BaseEvent.reset();
            CompleteMemberDetail detail_deviceId = TypeObjectUtils::build_complete_member_detail(name_deviceId, member_ann_builtin_deviceId, ann_custom_BaseEvent);
            CompleteStructMember member_deviceId = TypeObjectUtils::build_complete_struct_member(common_deviceId, detail_deviceId);
            TypeObjectUtils::add_complete_struct_member(member_seq_BaseEvent, member_deviceId);
        }
        CompleteStructType struct_type_BaseEvent = TypeObjectUtils::build_complete_struct_type(struct_flags_BaseEvent, header_BaseEvent, member_seq_BaseEvent);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_BaseEvent, type_name_BaseEvent.to_string(), type_ids_BaseEvent))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "casia::event::BaseEvent already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace event

} // namespace casia

