// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BaseEventPublisherApp.cxx
 * This file contains the implementation of the publisher functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "BaseEventPublisherApp.hpp"

#include <condition_variable>
#include <csignal>
#include <stdexcept>
#include <thread>

#include <QSettings>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/publisher/qos/DataWriterQos.hpp>
#include <fastdds/dds/publisher/qos/PublisherQos.hpp>

#include "BaseEventPubSubTypes.hpp"

using namespace eprosima::fastdds::dds;

namespace {
struct BaseEventPubDdsConfig {
    bool useProfile = false;
    QString xmlFile = QStringLiteral("alarmevent_multi.xml");
    QString participantProfile = QStringLiteral("participant_baseevent_pub");
    QString topicName = QStringLiteral("BaseEventTopic");
};

BaseEventPubDdsConfig loadBaseEventPubDdsConfig()
{
    BaseEventPubDdsConfig c;
    QSettings s(QStringLiteral("Config.ini"), QSettings::IniFormat);
    c.useProfile = s.value(QStringLiteral("DDS/BaseEventPubUseProfile"), 0).toInt() != 0;
    c.xmlFile = s.value(QStringLiteral("DDS/BaseEventPubXml"), c.xmlFile).toString();
    c.participantProfile = s.value(QStringLiteral("DDS/BaseEventPubParticipantProfile"), c.participantProfile).toString();
    c.topicName = s.value(QStringLiteral("DDS/BaseEventPubTopic"), c.topicName).toString();
    return c;
}
}

BaseEventPublisherApp::BaseEventPublisherApp(
        const int& domain_id)
    : factory_(nullptr)
    , participant_(nullptr)
    , publisher_(nullptr)
    , topic_(nullptr)
    , writer_(nullptr)
    , type_(new casia::event::BaseEventPubSubType())
    , matched_(0)
    , samples_sent_(0)
    , stop_(false)
{
    const BaseEventPubDdsConfig ddsCfg = loadBaseEventPubDdsConfig();
    //

    // Create the participant
    DomainParticipantQos pqos = PARTICIPANT_QOS_DEFAULT;
    pqos.name("casia::event::BaseEvent_pub_participant");
    factory_ = DomainParticipantFactory::get_shared_instance();
    if (ddsCfg.useProfile) {
        factory_->load_XML_profiles_file(ddsCfg.xmlFile.toStdString());
        participant_ = factory_->create_participant_with_profile(domain_id, ddsCfg.participantProfile.toStdString());
    } else {
        participant_ = factory_->create_participant(domain_id, pqos, nullptr, StatusMask::none());
    }
    if (participant_ == nullptr)
    {
        throw std::runtime_error("casia::event::BaseEvent Participant initialization failed");
    }

    // Register the type
    type_.register_type(participant_);

    // Create the publisher
    PublisherQos pub_qos = PUBLISHER_QOS_DEFAULT;
    participant_->get_default_publisher_qos(pub_qos);
    publisher_ = participant_->create_publisher(pub_qos, nullptr, StatusMask::none());
    if (publisher_ == nullptr)
    {
        throw std::runtime_error("casia::event::BaseEvent Publisher initialization failed");
    }

    // Create the topic
    TopicQos topic_qos = TOPIC_QOS_DEFAULT;
    participant_->get_default_topic_qos(topic_qos);
    topic_ = participant_->create_topic(ddsCfg.topicName.toStdString(), type_.get_type_name(), topic_qos);
    if (topic_ == nullptr)
    {
        throw std::runtime_error("casia::event::BaseEvent Topic initialization failed");
    }

    // Create the data writer
    DataWriterQos writer_qos = DATAWRITER_QOS_DEFAULT;
    publisher_->get_default_datawriter_qos(writer_qos);
    writer_qos.reliability().kind = ReliabilityQosPolicyKind::RELIABLE_RELIABILITY_QOS;
    writer_qos.durability().kind = DurabilityQosPolicyKind::TRANSIENT_LOCAL_DURABILITY_QOS;
    writer_qos.history().kind = HistoryQosPolicyKind::KEEP_ALL_HISTORY_QOS;
    writer_ = publisher_->create_datawriter(topic_, writer_qos, this, StatusMask::all());
    if (writer_ == nullptr)
    {
        throw std::runtime_error("casia::event::BaseEvent DataWriter initialization failed");
    }
}

BaseEventPublisherApp::~BaseEventPublisherApp()
{
    if (nullptr != participant_)
    {
        // Delete DDS entities contained within the DomainParticipant
        participant_->delete_contained_entities();

        // Delete DomainParticipant
        if (factory_)
            factory_->delete_participant(participant_);
        else
            DomainParticipantFactory::get_instance()->delete_participant(participant_);
    }
}

void BaseEventPublisherApp::on_publication_matched(
        DataWriter* /*writer*/,
        const PublicationMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        {
            std::lock_guard<std::mutex> lock(mutex_);
            matched_ = info.current_count;
        }
        std::cout << "casia::event::BaseEvent Publisher matched." << std::endl;
        cv_.notify_one();
    }
    else if (info.current_count_change == -1)
    {
        {
            std::lock_guard<std::mutex> lock(mutex_);
            matched_ = info.current_count;
        }
        std::cout << "casia::event::BaseEvent Publisher unmatched." << std::endl;
    }
    else
    {
        std::cout << info.current_count_change
                  << " is not a valid value for PublicationMatchedStatus current count change" << std::endl;
    }
}

void BaseEventPublisherApp::run()
{
    while (!is_stopped())
    {
        if (publish())
        {
            std::cout << "Sample '" << std::to_string(++samples_sent_) << "' SENT" << std::endl;
        }
        // Wait for period or stop event
        std::unique_lock<std::mutex> period_lock(mutex_);
        cv_.wait_for(period_lock, std::chrono::milliseconds(period_ms_), [this]()
                {
                    return is_stopped();
                });
    }
}


bool BaseEventPublisherApp::publish()
{
    bool ret = false;
    // Wait for the data endpoints discovery
    std::unique_lock<std::mutex> matched_lock(mutex_);
    cv_.wait(matched_lock, [&]()
            {
                // at least one has been discovered
                return ((matched_ > 0) || is_stopped());
            });

    if (!is_stopped())
    {
        /* Initialize your structure here */
        casia::event::BaseEvent sample_;
        ret = (RETCODE_OK == writer_->write(&sample_));
    }
    return ret;
}

bool BaseEventPublisherApp::is_stopped()
{
    return stop_.load();
}

void BaseEventPublisherApp::stop()
{
    stop_.store(true);
    cv_.notify_one();
}