// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BaseEvent.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__CASIA_EVENT_BASEEVENT_HPP
#define FAST_DDS_GENERATED__CASIA_EVENT_BASEEVENT_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BASEEVENT_SOURCE)
#define BASEEVENT_DllAPI __declspec( dllexport )
#else
#define BASEEVENT_DllAPI __declspec( dllimport )
#endif // BASEEVENT_SOURCE
#else
#define BASEEVENT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BASEEVENT_DllAPI
#endif // _WIN32

namespace casia {

namespace event {

/*!
 * @brief This class represents the enumeration EventSeverity defined by the user in the IDL file.
 * @ingroup BaseEvent
 */
enum class EventSeverity : int32_t
{
    INFO,
    WARNING,
    ERROR_,
    CRITICAL
};
/*!
 * @brief This class represents the enumeration EventSourceType defined by the user in the IDL file.
 * @ingroup BaseEvent
 */
enum class EventSourceType : int32_t
{
    SYSTEM,
    DEVICE,
    USER,
    TASK,
    TRACK
};
/*!
 * @brief This class represents the structure BaseEvent defined by the user in the IDL file.
 * @ingroup BaseEvent
 */
class BaseEvent
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport BaseEvent()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~BaseEvent()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object BaseEvent that will be copied.
     */
    eProsima_user_DllExport BaseEvent(
            const BaseEvent& x)
    {
                    m_eventId = x.m_eventId;

                    m_sourceId = x.m_sourceId;

                    m_sourceType = x.m_sourceType;

                    m_severity = x.m_severity;

                    m_message = x.m_message;

                    m_timestamp = x.m_timestamp;

                    m_userId = x.m_userId;

                    m_deviceId = x.m_deviceId;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object BaseEvent that will be copied.
     */
    eProsima_user_DllExport BaseEvent(
            BaseEvent&& x) noexcept
    {
        m_eventId = std::move(x.m_eventId);
        m_sourceId = std::move(x.m_sourceId);
        m_sourceType = x.m_sourceType;
        m_severity = x.m_severity;
        m_message = std::move(x.m_message);
        m_timestamp = std::move(x.m_timestamp);
        m_userId = std::move(x.m_userId);
        m_deviceId = std::move(x.m_deviceId);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object BaseEvent that will be copied.
     */
    eProsima_user_DllExport BaseEvent& operator =(
            const BaseEvent& x)
    {

                    m_eventId = x.m_eventId;

                    m_sourceId = x.m_sourceId;

                    m_sourceType = x.m_sourceType;

                    m_severity = x.m_severity;

                    m_message = x.m_message;

                    m_timestamp = x.m_timestamp;

                    m_userId = x.m_userId;

                    m_deviceId = x.m_deviceId;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object BaseEvent that will be copied.
     */
    eProsima_user_DllExport BaseEvent& operator =(
            BaseEvent&& x) noexcept
    {

        m_eventId = std::move(x.m_eventId);
        m_sourceId = std::move(x.m_sourceId);
        m_sourceType = x.m_sourceType;
        m_severity = x.m_severity;
        m_message = std::move(x.m_message);
        m_timestamp = std::move(x.m_timestamp);
        m_userId = std::move(x.m_userId);
        m_deviceId = std::move(x.m_deviceId);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x BaseEvent object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const BaseEvent& x) const
    {
        return (m_eventId == x.m_eventId &&
           m_sourceId == x.m_sourceId &&
           m_sourceType == x.m_sourceType &&
           m_severity == x.m_severity &&
           m_message == x.m_message &&
           m_timestamp == x.m_timestamp &&
           m_userId == x.m_userId &&
           m_deviceId == x.m_deviceId);
    }

    /*!
     * @brief Comparison operator.
     * @param x BaseEvent object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const BaseEvent& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member eventId
     * @param _eventId New value to be copied in member eventId
     */
    eProsima_user_DllExport void eventId(
            const std::string& _eventId)
    {
        m_eventId = _eventId;
    }

    /*!
     * @brief This function moves the value in member eventId
     * @param _eventId New value to be moved in member eventId
     */
    eProsima_user_DllExport void eventId(
            std::string&& _eventId)
    {
        m_eventId = std::move(_eventId);
    }

    /*!
     * @brief This function returns a constant reference to member eventId
     * @return Constant reference to member eventId
     */
    eProsima_user_DllExport const std::string& eventId() const
    {
        return m_eventId;
    }

    /*!
     * @brief This function returns a reference to member eventId
     * @return Reference to member eventId
     */
    eProsima_user_DllExport std::string& eventId()
    {
        return m_eventId;
    }


    /*!
     * @brief This function copies the value in member sourceId
     * @param _sourceId New value to be copied in member sourceId
     */
    eProsima_user_DllExport void sourceId(
            const std::string& _sourceId)
    {
        m_sourceId = _sourceId;
    }

    /*!
     * @brief This function moves the value in member sourceId
     * @param _sourceId New value to be moved in member sourceId
     */
    eProsima_user_DllExport void sourceId(
            std::string&& _sourceId)
    {
        m_sourceId = std::move(_sourceId);
    }

    /*!
     * @brief This function returns a constant reference to member sourceId
     * @return Constant reference to member sourceId
     */
    eProsima_user_DllExport const std::string& sourceId() const
    {
        return m_sourceId;
    }

    /*!
     * @brief This function returns a reference to member sourceId
     * @return Reference to member sourceId
     */
    eProsima_user_DllExport std::string& sourceId()
    {
        return m_sourceId;
    }


    /*!
     * @brief This function sets a value in member sourceType
     * @param _sourceType New value for member sourceType
     */
    eProsima_user_DllExport void sourceType(
            EventSourceType _sourceType)
    {
        m_sourceType = _sourceType;
    }

    /*!
     * @brief This function returns the value of member sourceType
     * @return Value of member sourceType
     */
    eProsima_user_DllExport EventSourceType sourceType() const
    {
        return m_sourceType;
    }

    /*!
     * @brief This function returns a reference to member sourceType
     * @return Reference to member sourceType
     */
    eProsima_user_DllExport EventSourceType& sourceType()
    {
        return m_sourceType;
    }


    /*!
     * @brief This function sets a value in member severity
     * @param _severity New value for member severity
     */
    eProsima_user_DllExport void severity(
            EventSeverity _severity)
    {
        m_severity = _severity;
    }

    /*!
     * @brief This function returns the value of member severity
     * @return Value of member severity
     */
    eProsima_user_DllExport EventSeverity severity() const
    {
        return m_severity;
    }

    /*!
     * @brief This function returns a reference to member severity
     * @return Reference to member severity
     */
    eProsima_user_DllExport EventSeverity& severity()
    {
        return m_severity;
    }


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message)
    {
        m_message = _message;
    }

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message)
    {
        m_message = std::move(_message);
    }

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const
    {
        return m_message;
    }

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message()
    {
        return m_message;
    }


    /*!
     * @brief This function copies the value in member timestamp
     * @param _timestamp New value to be copied in member timestamp
     */
    eProsima_user_DllExport void timestamp(
            const std::string& _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function moves the value in member timestamp
     * @param _timestamp New value to be moved in member timestamp
     */
    eProsima_user_DllExport void timestamp(
            std::string&& _timestamp)
    {
        m_timestamp = std::move(_timestamp);
    }

    /*!
     * @brief This function returns a constant reference to member timestamp
     * @return Constant reference to member timestamp
     */
    eProsima_user_DllExport const std::string& timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport std::string& timestamp()
    {
        return m_timestamp;
    }


    /*!
     * @brief This function copies the value in member userId
     * @param _userId New value to be copied in member userId
     */
    eProsima_user_DllExport void userId(
            const std::string& _userId)
    {
        m_userId = _userId;
    }

    /*!
     * @brief This function moves the value in member userId
     * @param _userId New value to be moved in member userId
     */
    eProsima_user_DllExport void userId(
            std::string&& _userId)
    {
        m_userId = std::move(_userId);
    }

    /*!
     * @brief This function returns a constant reference to member userId
     * @return Constant reference to member userId
     */
    eProsima_user_DllExport const std::string& userId() const
    {
        return m_userId;
    }

    /*!
     * @brief This function returns a reference to member userId
     * @return Reference to member userId
     */
    eProsima_user_DllExport std::string& userId()
    {
        return m_userId;
    }


    /*!
     * @brief This function copies the value in member deviceId
     * @param _deviceId New value to be copied in member deviceId
     */
    eProsima_user_DllExport void deviceId(
            const std::vector<std::string>& _deviceId)
    {
        m_deviceId = _deviceId;
    }

    /*!
     * @brief This function moves the value in member deviceId
     * @param _deviceId New value to be moved in member deviceId
     */
    eProsima_user_DllExport void deviceId(
            std::vector<std::string>&& _deviceId)
    {
        m_deviceId = std::move(_deviceId);
    }

    /*!
     * @brief This function returns a constant reference to member deviceId
     * @return Constant reference to member deviceId
     */
    eProsima_user_DllExport const std::vector<std::string>& deviceId() const
    {
        return m_deviceId;
    }

    /*!
     * @brief This function returns a reference to member deviceId
     * @return Reference to member deviceId
     */
    eProsima_user_DllExport std::vector<std::string>& deviceId()
    {
        return m_deviceId;
    }



private:

    std::string m_eventId;
    std::string m_sourceId;
    EventSourceType m_sourceType{EventSourceType::SYSTEM};
    EventSeverity m_severity{EventSeverity::INFO};
    std::string m_message;
    std::string m_timestamp;
    std::string m_userId;
    std::vector<std::string> m_deviceId;

};

} // namespace event

} // namespace casia

#endif // _FAST_DDS_GENERATED_CASIA_EVENT_BASEEVENT_HPP_


